% clear workspace and close open figure windows
clear
close all

% load data
load(['/home/herman_lab/Documents/PLDAPS_vK2_MASTER/output' ...
    '/20240603_t1023_joystick_release_for_stim_change_and_dim'])

% close opened figure windows AGAIN
close all

% define useful variables
isStimChangeTrial   = [trVars.isStimChangeTrial];
isNoChangeTrial     = [trVars.isNoChangeTrial];
trialEndState       = [trData.trialEndState];
reactionTime        = arrayfun(@(x)x.timing.reactionTime, trData)';
stimChangeTime      = [trVars.stimChangeTime];

% compute binomial parameter fits and associated confidence intervals:
[p(1), pci(1,:)] = binofit(...
    nnz(trialEndState == state.fa & isStimChangeTrial), ...
    nnz(isStimChangeTrial & trialEndState>20));
[p(2), pci(2,:)] = binofit(...
    nnz(trialEndState == state.fa & isNoChangeTrial), ...
    nnz(isNoChangeTrial & trialEndState>20));

% plot
figure('Color', [1 1 1]);
errorbar(1:2,p,p - pci(:,1)', pci(:,2)' - p);
set(gca, ...
    'XLim', [0 3], ...
    'YLim', [0 1], ...
    'XTick', [1 2], ...
    'XTickLabel', {'Change', 'NO change'}, ...
    'YTick', 0:0.25:1, ...
    'TickDir', 'Out', ...
    'LineWidth', 1, ...
    'FontSize', 16, 'Box','Off');