function p = plotWindowSetup(p)

% Online plotting window for the LRS conflict task.
%
% Layout:
%   left column  : behavioral plots
%   right column : status panel

%% ------------------------------------------------------------
% Layout positions
% ------------------------------------------------------------

% Left column plots
RewardPosition          = [0.07 0.65 0.60 0.30];
PHighSalPosition        = [0.07 0.40 0.27 0.17];
MedianRTPosition        = [0.40 0.40 0.27 0.17];
ChoiceEvolutionPosition = [0.07 0.05 0.60 0.30];

% Right column status panel
StatusPosition          = [0.72 0.10 0.27 0.85];

%% ------------------------------------------------------------
% Initialize online plot data storage
% ------------------------------------------------------------

p.status.onlinePlot.trial         = [];
p.status.onlinePlot.trialType     = [];   % 1 = congruent, 2 = conflict
p.status.onlinePlot.choseHighSal  = [];   % 1 = chose high salience, 0 = did not, NaN = invalid
p.status.onlinePlot.rtMs          = [];   % reaction time in ms, NaN = invalid

%% ------------------------------------------------------------
% Create online plotting window
% ------------------------------------------------------------

% If there is already an online plotting window open, delete it
oldWin = findobj('Name', 'OnlinePlotWindow');
if ~isempty(oldWin)
    delete(oldWin);
end

% Create new plotting window
p.draw.onlinePlotWindow = figure( ...
    'Position', [1000 150 1200 1100], ...
    'Name', 'OnlinePlotWindow', ...
    'NumberTitle', 'off', ...
    'Color', [1 1 1], ...
    'Visible', 'off', ...
    'NextPlot', 'add');

% Only build axes and objects if online plots are requested
if isfield(p.trVarsInit, 'wantOnlinePlots') && p.trVarsInit.wantOnlinePlots

    %% ------------------------------------------------------------
    % Axes 1: Reward difference T1 - T2
    % ------------------------------------------------------------

    p.draw.onlinePlotAxes.rewardDiff = axes( ...
        'Parent', p.draw.onlinePlotWindow, ...
        'Units', 'normalized', ...
        'Position', RewardPosition, ...
        'TickDir', 'out', ...
        'LineWidth', 1, ...
        'XColor', [0 0 0], ...
        'YColor', [0 0 0], ...
        'NextPlot', 'add');

    hold(p.draw.onlinePlotAxes.rewardDiff, 'on');
    box(p.draw.onlinePlotAxes.rewardDiff, 'off');

    title(p.draw.onlinePlotAxes.rewardDiff, ...
        'Reward difference across trials', ...
        'FontSize', 14, ...
        'FontWeight', 'bold');

    xlabel(p.draw.onlinePlotAxes.rewardDiff, ...
        'Trial number', ...
        'FontSize', 11);

    ylabel(p.draw.onlinePlotAxes.rewardDiff, ...
        'T1 - T2 reward (ms)', ...
        'FontSize', 11);

    % Zero line
    p.draw.onlinePlotObj.rewardZero = plot( ...
        p.draw.onlinePlotAxes.rewardDiff, ...
        [0 10], [0 0], ...
        'LineStyle', ':', ...
        'Color', [0 0 0], ...
        'LineWidth', 1.3);

    % Reward difference line
    p.draw.onlinePlotObj.rewardDiff = plot( ...
        p.draw.onlinePlotAxes.rewardDiff, ...
        NaN, NaN, ...
        'LineStyle', '-', ...
        'Marker', '.', ...
        'Color', [0.00 0.45 0.74], ...
        'LineWidth', 1.5, ...
        'MarkerSize', 10);

    text( ...
        p.draw.onlinePlotAxes.rewardDiff, ...
        0.02, 0.88, ...
        'Positive = T1 richer', ...
        'Units', 'normalized', ...
        'FontSize', 10);

    text( ...
        p.draw.onlinePlotAxes.rewardDiff, ...
        0.02, 0.10, ...
        'Negative = T2 richer', ...
        'Units', 'normalized', ...
        'FontSize', 10);

    set(p.draw.onlinePlotAxes.rewardDiff, ...
        'XLim', [0 10], ...
        'YLim', [-200 200]);

    %% ------------------------------------------------------------
    % Axes 2: P(High Salience), Conflict vs Congruent
    % ------------------------------------------------------------

    p.draw.onlinePlotAxes.pHighSal = axes( ...
        'Parent', p.draw.onlinePlotWindow, ...
        'Units', 'normalized', ...
        'Position', PHighSalPosition, ...
        'TickDir', 'out', ...
        'LineWidth', 1, ...
        'XColor', [0 0 0], ...
        'YColor', [0 0 0], ...
        'NextPlot', 'add');

    hold(p.draw.onlinePlotAxes.pHighSal, 'on');
    box(p.draw.onlinePlotAxes.pHighSal, 'off');

    title(p.draw.onlinePlotAxes.pHighSal, ...
        'P(High Salience)', ...
        'FontSize', 14, ...
        'FontWeight', 'bold');

    ylabel(p.draw.onlinePlotAxes.pHighSal, ...
        'Probability', ...
        'FontSize', 11);

    set(p.draw.onlinePlotAxes.pHighSal, ...
        'XLim', [0.5 2.5], ...
        'YLim', [0 1], ...
        'XTick', [1 2], ...
        'XTickLabel', {'Conflict', 'Congruent'});

    p.draw.onlinePlotObj.pHighSalChance = plot( ...
        p.draw.onlinePlotAxes.pHighSal, ...
        [0.5 2.5], [0.5 0.5], ...
        'LineStyle', '--', ...
        'Color', 0.75 * [1 1 1], ...
        'LineWidth', 1.2);

    p.draw.onlinePlotObj.pHighSalConflict = bar( ...
        p.draw.onlinePlotAxes.pHighSal, ...
        1, NaN, 0.55, ...
        'FaceColor', [0.85 0.33 0.10], ...
        'EdgeColor', 'none');

    p.draw.onlinePlotObj.pHighSalCongruent = bar( ...
        p.draw.onlinePlotAxes.pHighSal, ...
        2, NaN, 0.55, ...
        'FaceColor', [0.00 0.45 0.74], ...
        'EdgeColor', 'none');

    %% ------------------------------------------------------------
    % Axes 3: Median RT, Conflict vs Congruent
    % ------------------------------------------------------------

    p.draw.onlinePlotAxes.medianRT = axes( ...
        'Parent', p.draw.onlinePlotWindow, ...
        'Units', 'normalized', ...
        'Position', MedianRTPosition, ...
        'TickDir', 'out', ...
        'LineWidth', 1, ...
        'XColor', [0 0 0], ...
        'YColor', [0 0 0], ...
        'NextPlot', 'add');

    hold(p.draw.onlinePlotAxes.medianRT, 'on');
    box(p.draw.onlinePlotAxes.medianRT, 'off');

    title(p.draw.onlinePlotAxes.medianRT, ...
        'Median RT', ...
        'FontSize', 14, ...
        'FontWeight', 'bold');

    ylabel(p.draw.onlinePlotAxes.medianRT, ...
        'RT (ms)', ...
        'FontSize', 11);

    set(p.draw.onlinePlotAxes.medianRT, ...
        'XLim', [0.5 2.5], ...
        'YLim', [0 500], ...
        'XTick', [1 2], ...
        'XTickLabel', {'Conflict', 'Congruent'});

    p.draw.onlinePlotObj.medianRTConflict = bar( ...
        p.draw.onlinePlotAxes.medianRT, ...
        1, NaN, 0.55, ...
        'FaceColor', [0.85 0.33 0.10], ...
        'EdgeColor', 'none');

    p.draw.onlinePlotObj.medianRTCongruent = bar( ...
        p.draw.onlinePlotAxes.medianRT, ...
        2, NaN, 0.55, ...
        'FaceColor', [0.00 0.45 0.74], ...
        'EdgeColor', 'none');

    %% ------------------------------------------------------------
    % Axes 4: Choice evolution over session
    % ------------------------------------------------------------

    p.draw.onlinePlotAxes.choiceEvolution = axes( ...
        'Parent', p.draw.onlinePlotWindow, ...
        'Units', 'normalized', ...
        'Position', ChoiceEvolutionPosition, ...
        'TickDir', 'out', ...
        'LineWidth', 1, ...
        'XColor', [0 0 0], ...
        'YColor', [0 0 0], ...
        'NextPlot', 'add');

    hold(p.draw.onlinePlotAxes.choiceEvolution, 'on');
    box(p.draw.onlinePlotAxes.choiceEvolution, 'off');

    title(p.draw.onlinePlotAxes.choiceEvolution, ...
        'Choice evolution over session', ...
        'FontSize', 14, ...
        'FontWeight', 'bold');

    xlabel(p.draw.onlinePlotAxes.choiceEvolution, ...
        'Trial number', ...
        'FontSize', 11);

    ylabel(p.draw.onlinePlotAxes.choiceEvolution, ...
        'Cumulative P(High Sal)', ...
        'FontSize', 11);

    set(p.draw.onlinePlotAxes.choiceEvolution, ...
        'XLim', [0 10], ...
        'YLim', [0 1]);

    p.draw.onlinePlotObj.choiceChance = plot( ...
        p.draw.onlinePlotAxes.choiceEvolution, ...
        [0 10], [0.5 0.5], ...
        'LineStyle', '--', ...
        'Color', 0.80 * [1 1 1], ...
        'LineWidth', 1.2);

    p.draw.onlinePlotObj.choiceConflict = plot( ...
        p.draw.onlinePlotAxes.choiceEvolution, ...
        NaN, NaN, ...
        'LineStyle', '-', ...
        'Color', [0.85 0.33 0.10], ...
        'LineWidth', 2);

    p.draw.onlinePlotObj.choiceCongruent = plot( ...
        p.draw.onlinePlotAxes.choiceEvolution, ...
        NaN, NaN, ...
        'LineStyle', '-', ...
        'Color', [0.00 0.45 0.74], ...
        'LineWidth', 2);

    p.draw.onlinePlotObj.choiceOverall = plot( ...
        p.draw.onlinePlotAxes.choiceEvolution, ...
        NaN, NaN, ...
        'LineStyle', '--', ...
        'Color', [0.20 0.20 0.20], ...
        'LineWidth', 1.5);

    legend( ...
        p.draw.onlinePlotAxes.choiceEvolution, ...
        [p.draw.onlinePlotObj.choiceConflict, ...
         p.draw.onlinePlotObj.choiceCongruent, ...
         p.draw.onlinePlotObj.choiceOverall], ...
        {'Conflict', 'Congruent', 'Overall'}, ...
        'Location', 'southoutside', ...
        'Orientation', 'horizontal');

    %% ------------------------------------------------------------
    % Status display panel
    % ------------------------------------------------------------

    p.draw.onlinePlotObj.statusText = uicontrol( ...
        'Parent', p.draw.onlinePlotWindow, ...
        'Style', 'listbox', ...
        'Units', 'normalized', ...
        'Position', StatusPosition, ...
        'BackgroundColor', [0.97 0.97 0.97], ...
        'ForegroundColor', [0 0 0], ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'FixedWidth', ...
        'FontSize', 10, ...
        'String', {'Status will appear here'});

    set(p.draw.onlinePlotWindow, 'Visible', 'on');
end

end
