function p = extraWindowSetup(p)
%   p = extraWindowSetup(p)
%
% Initialize plotting windows for the Conflict Task.
% Creates the tachometric curve figure and optional gaze plots.

%% Create Tachometric Curve Figure
% This is the primary visualization for the Conflict Task

% Close existing figure if present
tachFigHandle = findall(0, 'Name', 'Conflict Task - Tachometric Curve');
if ~isempty(tachFigHandle)
    close(tachFigHandle)
end

% Create new figure
p.draw.tachFig = figure(...
    'Position', [1220 200 900 800], ...
    'Name', 'Conflict Task - Tachometric Curve', ...
    'NumberTitle', 'off', ...
    'Color', [1 1 1], ...
    'Visible', 'on', ...
    'NextPlot', 'add');

% Define colors
conflictColor = [0.850 0.325 0.098];   % Orange for Conflict
congruentColor = [0.000 0.447 0.741];  % Blue for Congruent
goalColor = [0.466 0.674 0.188];       % Green for goal-directed
captureColor = [0.635 0.078 0.184];    % Red for capture

%% Tachometric Curve Axes (top panel)
p.draw.tachAxes = axes(...
    'Parent', p.draw.tachFig, ...
    'Position', [0.10 0.55 0.85 0.38], ...
    'TickDir', 'out', ...
    'LineWidth', 1.5, ...
    'NextPlot', 'add', ...
    'XLim', [-175 125], ...
    'YLim', [0 1], ...
    'XTick', [-150 -100 -50 0 50 100], ...
    'YTick', [0 0.25 0.5 0.75 1], ...
    'FontSize', 11);

xlabel(p.draw.tachAxes, '\Deltat (ms) - Stimulus onset relative to Go signal', ...
    'FontSize', 13);
ylabel(p.draw.tachAxes, 'P(Goal-Directed Choice)', 'FontSize', 13);
title(p.draw.tachAxes, 'Tachometric Curve', 'FontSize', 14, 'FontWeight', 'bold');

% Add reference lines
plot(p.draw.tachAxes, [-175 125], [0.5 0.5], '--', 'Color', [0.5 0.5 0.5], ...
    'LineWidth', 1);  % Chance level
plot(p.draw.tachAxes, [0 0], [0 1], '--', 'Color', [0.5 0.5 0.5], ...
    'LineWidth', 1);  % Zero delta-t

% Create line and scatter plot objects for tachometric curves
p.draw.plotObs.tachConflict = plot(p.draw.tachAxes, NaN, NaN, '-', ...
    'Color', conflictColor, 'LineWidth', 2.5);
p.draw.plotObs.tachConflictPts = scatter(p.draw.tachAxes, [], [], 80, ...
    conflictColor, 'filled', 'MarkerFaceAlpha', 0.8);

p.draw.plotObs.tachCongruent = plot(p.draw.tachAxes, NaN, NaN, '-', ...
    'Color', congruentColor, 'LineWidth', 2.5);
p.draw.plotObs.tachCongruentPts = scatter(p.draw.tachAxes, [], [], 80, ...
    congruentColor, 'filled', 'MarkerFaceAlpha', 0.8);

% Add legend
legend(p.draw.tachAxes, ...
    [p.draw.plotObs.tachConflict, p.draw.plotObs.tachCongruent], ...
    {'Conflict', 'Congruent'}, ...
    'Location', 'southeast', 'FontSize', 11, 'Box', 'off');

% Add text annotations explaining the axes
text(p.draw.tachAxes, -160, 0.95, 'Stimuli before Go', ...
    'FontSize', 9, 'Color', [0.4 0.4 0.4]);
text(p.draw.tachAxes, 60, 0.95, 'Stimuli after Go', ...
    'FontSize', 9, 'Color', [0.4 0.4 0.4]);

%% RT Comparison Axes (bottom left panel)
p.draw.rtAxes = axes(...
    'Parent', p.draw.tachFig, ...
    'Position', [0.10 0.10 0.35 0.32], ...
    'TickDir', 'out', ...
    'LineWidth', 1, ...
    'NextPlot', 'add', ...
    'XLim', [0.5 2.5], ...
    'YLim', [0 500], ...
    'XTick', [1 2], ...
    'XTickLabel', {'Goal-Directed', 'Capture'}, ...
    'FontSize', 10);

ylabel(p.draw.rtAxes, 'Mean RT (ms)', 'FontSize', 12);
title(p.draw.rtAxes, 'Reaction Time by Outcome', 'FontSize', 12);

% Create bar plot objects
p.draw.plotObs.rtBarGoal = bar(p.draw.rtAxes, 1, 0, 0.6, ...
    'FaceColor', goalColor, 'EdgeColor', 'none');
p.draw.plotObs.rtBarCapture = bar(p.draw.rtAxes, 2, 0, 0.6, ...
    'FaceColor', captureColor, 'EdgeColor', 'none');

%% Session Progress Panel (bottom right)
p.draw.progressAxes = axes(...
    'Parent', p.draw.tachFig, ...
    'Position', [0.55 0.10 0.40 0.32], ...
    'Visible', 'off');

% Block progress text
p.draw.blockText = text(p.draw.progressAxes, 0.5, 0.8, 'Block 1/6 | Trial 0/60', ...
    'FontSize', 16, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');

% Session info text
sessionInfoStr = sprintf('Session: %s\nLocation A: (%.1f, %.1f) deg', ...
    p.init.sessionId, p.trVarsInit.locationA_x, p.trVarsInit.locationA_y);
text(p.draw.progressAxes, 0.5, 0.4, sessionInfoStr, ...
    'FontSize', 11, 'HorizontalAlignment', 'center');

% Outcome summary (will be updated)
text(p.draw.progressAxes, 0.5, 0.1, ...
    'Goal-Directed: 0 | Capture: 0 | Errors: 0', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Color', [0.4 0.4 0.4]);

%% Optional: Gaze vs Time Figure (if wantOnlinePlots is true)
if p.trVarsInit.wantOnlinePlots

    p.draw.gazeVsTimeFig = figure(...
        'Position', [10 800 1200 600], ...
        'Name', 'Conflict Task - Gaze Traces', ...
        'NumberTitle', 'off', ...
        'Color', [1 1 1], ...
        'Visible', 'on', ...
        'NextPlot', 'add');

    % Eye position axes
    p.draw.gazePosPlotAxes = axes(...
        'Parent', p.draw.gazeVsTimeFig, ...
        'Position', [0.06 0.55 0.88 0.38], ...
        'TickDir', 'Out', ...
        'LineWidth', 1, ...
        'NextPlot', 'add', ...
        'Color', 'none');
    ylabel(p.draw.gazePosPlotAxes, 'Eye Position (deg)', 'FontSize', 12);

    % Eye velocity axes
    p.draw.gazeVelPlotAxes = axes(...
        'Parent', p.draw.gazeVsTimeFig, ...
        'Position', [0.06 0.10 0.88 0.38], ...
        'TickDir', 'Out', ...
        'LineWidth', 1, ...
        'NextPlot', 'add', ...
        'Color', 'none', ...
        'YLim', [0 1200]);
    xlabel(p.draw.gazeVelPlotAxes, 'Time from fixation acquisition (s)', 'FontSize', 12);
    ylabel(p.draw.gazeVelPlotAxes, 'Eye Velocity (deg/s)', 'FontSize', 12);

    % Create plot objects
    p.draw.plotObs.xGaze = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0.294 0 0.573], 'LineWidth', 1.5);
    p.draw.plotObs.yGaze = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0 0.424 0.820], 'LineWidth', 1.5);
    p.draw.plotObs.tgt = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0.047 0.482 0.863], 'LineWidth', 1);
    p.draw.plotObs.fix = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0.102 0.522 1.000], 'LineWidth', 1);
    p.draw.plotObs.eyeVel = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        'Color', [0 0 0], 'LineWidth', 1.5);
    p.draw.plotObs.sacOn = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        'Color', [0.882 0.745 0.416], 'LineWidth', 2);
    p.draw.plotObs.sacOff = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        'Color', [0.600 0.310 0], 'LineWidth', 2);
    p.draw.plotObs.vThresh = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        ':', 'LineWidth', 1.5, 'Color', [0.828 0.373 0.718]);

    % Add legends
    legend(p.draw.gazePosPlotAxes, ...
        [p.draw.plotObs.xGaze, p.draw.plotObs.yGaze], ...
        {'Eye X', 'Eye Y'}, 'Location', 'northwest', 'Box', 'off');
    legend(p.draw.gazeVelPlotAxes, ...
        [p.draw.plotObs.eyeVel, p.draw.plotObs.vThresh], ...
        {'Velocity', 'Threshold'}, 'Location', 'northwest', 'Box', 'off');
end

end
