function p = extraWindowSetup(p)
%   p = extraWindowSetup(p)
%
% Initialize plotting windows for the Conflict Task (refactored design).
% Creates a 5-panel visualization figure:
%   Panel 1: Phase 1 (1:1) by Hemifield - P(high salience) vs delta-t
%   Panel 2: Phase 1 (1:1) Collapsed - single line
%   Panel 3: Phases 2-3 Conflict/Congruent - P(high salience) vs delta-t
%   Panel 4: Cumulative Evolution - behavior over trial number
%   Panel 5: Session Progress - phase/trial counters

%% Close existing figure if present
tachFigHandle = findall(0, 'Name', 'Conflict Task - Online Visualization');
if ~isempty(tachFigHandle)
    close(tachFigHandle)
end

%% Create new figure
p.draw.vizFig = figure(...
    'Position', [1220 50 1000 950], ...
    'Name', 'Conflict Task - Online Visualization', ...
    'NumberTitle', 'off', ...
    'Color', [1 1 1], ...
    'Visible', 'on', ...
    'NextPlot', 'add');

%% Define colors
highSalLeftColor = [0.850 0.325 0.098];   % Orange for High Salience Left
highSalRightColor = [0.000 0.447 0.741];  % Blue for High Salience Right
conflictColor = [0.850 0.325 0.098];      % Orange for Conflict
congruentColor = [0.000 0.447 0.741];     % Blue for Congruent
collapsedColor = [0.4 0.4 0.4];           % Gray for collapsed

% Delta-t values for x-axis
deltaTValues = p.status.deltaTValues;  % [-150, 150]

%% Panel 1: Phase 1 (1:1) by Hemifield (top left)
p.draw.panel1Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.08 0.72 0.40 0.22], ...
    'TickDir', 'out', ...
    'LineWidth', 1.5, ...
    'NextPlot', 'add', ...
    'XLim', [-200 200], ...
    'YLim', [0 1], ...
    'XTick', deltaTValues, ...
    'YTick', [0 0.25 0.5 0.75 1], ...
    'FontSize', 10);

xlabel(p.draw.panel1Axes, '\Deltat (ms)', 'FontSize', 11);
ylabel(p.draw.panel1Axes, 'P(High Salience)', 'FontSize', 11);
title(p.draw.panel1Axes, 'Phase 1 (1:1) - By Hemifield', 'FontSize', 12, 'FontWeight', 'bold');

% Reference line at 0.5
plot(p.draw.panel1Axes, [-200 200], [0.5 0.5], '--', 'Color', [0.7 0.7 0.7], 'LineWidth', 1);

% Create plot objects for Phase 1 by hemifield
p.draw.plotObs.p1_highSalLeft = plot(p.draw.panel1Axes, NaN, NaN, '-o', ...
    'Color', highSalLeftColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', highSalLeftColor);
p.draw.plotObs.p1_highSalRight = plot(p.draw.panel1Axes, NaN, NaN, '-o', ...
    'Color', highSalRightColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', highSalRightColor);

legend(p.draw.panel1Axes, ...
    [p.draw.plotObs.p1_highSalLeft, p.draw.plotObs.p1_highSalRight], ...
    {'High Sal LEFT', 'High Sal RIGHT'}, ...
    'Location', 'southeast', 'FontSize', 9, 'Box', 'off');

%% Panel 2: Phase 1 (1:1) Collapsed (top right)
p.draw.panel2Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.56 0.72 0.40 0.22], ...
    'TickDir', 'out', ...
    'LineWidth', 1.5, ...
    'NextPlot', 'add', ...
    'XLim', [-200 200], ...
    'YLim', [0 1], ...
    'XTick', deltaTValues, ...
    'YTick', [0 0.25 0.5 0.75 1], ...
    'FontSize', 10);

xlabel(p.draw.panel2Axes, '\Deltat (ms)', 'FontSize', 11);
ylabel(p.draw.panel2Axes, 'P(High Salience)', 'FontSize', 11);
title(p.draw.panel2Axes, 'Phase 1 (1:1) - Collapsed', 'FontSize', 12, 'FontWeight', 'bold');

% Reference line at 0.5
plot(p.draw.panel2Axes, [-200 200], [0.5 0.5], '--', 'Color', [0.7 0.7 0.7], 'LineWidth', 1);

% Create plot object for Phase 1 collapsed
p.draw.plotObs.p1_collapsed = plot(p.draw.panel2Axes, NaN, NaN, '-o', ...
    'Color', collapsedColor, 'LineWidth', 2.5, 'MarkerSize', 10, 'MarkerFaceColor', collapsedColor);

%% Panel 3: Phases 2-3 Conflict vs Congruent (middle)
p.draw.panel3Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.08 0.42 0.88 0.22], ...
    'TickDir', 'out', ...
    'LineWidth', 1.5, ...
    'NextPlot', 'add', ...
    'XLim', [-200 200], ...
    'YLim', [0 1], ...
    'XTick', deltaTValues, ...
    'YTick', [0 0.25 0.5 0.75 1], ...
    'FontSize', 10);

xlabel(p.draw.panel3Axes, '\Deltat (ms)', 'FontSize', 11);
ylabel(p.draw.panel3Axes, 'P(High Salience)', 'FontSize', 11);
title(p.draw.panel3Axes, 'Phases 2-3 (Asymmetric Reward) - Conflict vs Congruent', ...
    'FontSize', 12, 'FontWeight', 'bold');

% Reference line at 0.5
plot(p.draw.panel3Axes, [-200 200], [0.5 0.5], '--', 'Color', [0.7 0.7 0.7], 'LineWidth', 1);

% Create plot objects for Phases 2-3
p.draw.plotObs.p23_conflict = plot(p.draw.panel3Axes, NaN, NaN, '-o', ...
    'Color', conflictColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', conflictColor);
p.draw.plotObs.p23_congruent = plot(p.draw.panel3Axes, NaN, NaN, '-o', ...
    'Color', congruentColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', congruentColor);

legend(p.draw.panel3Axes, ...
    [p.draw.plotObs.p23_conflict, p.draw.plotObs.p23_congruent], ...
    {'Conflict (Sal opposes Reward)', 'Congruent (Sal aligns with Reward)'}, ...
    'Location', 'southeast', 'FontSize', 9, 'Box', 'off');

%% Panel 4: Cumulative Evolution (bottom left)
p.draw.panel4Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.08 0.08 0.55 0.26], ...
    'TickDir', 'out', ...
    'LineWidth', 1.5, ...
    'NextPlot', 'add', ...
    'XLim', [0 400], ...
    'YLim', [0 1], ...
    'YTick', [0 0.25 0.5 0.75 1], ...
    'FontSize', 10);

xlabel(p.draw.panel4Axes, 'Trial Number', 'FontSize', 11);
ylabel(p.draw.panel4Axes, 'Cumulative P(High Salience)', 'FontSize', 11);
title(p.draw.panel4Axes, 'Choice Evolution Over Session', 'FontSize', 12, 'FontWeight', 'bold');

% Reference line at 0.5
plot(p.draw.panel4Axes, [0 400], [0.5 0.5], '--', 'Color', [0.7 0.7 0.7], 'LineWidth', 1);

% Phase transition lines
p.draw.plotObs.phaseLine1 = plot(p.draw.panel4Axes, [128 128], [0 1], ':', ...
    'Color', [0.5 0.5 0.5], 'LineWidth', 1.5);
p.draw.plotObs.phaseLine2 = plot(p.draw.panel4Axes, [256 256], [0 1], ':', ...
    'Color', [0.5 0.5 0.5], 'LineWidth', 1.5);

% Phase labels
text(p.draw.panel4Axes, 64, 0.97, 'Phase 1', 'FontSize', 9, ...
    'HorizontalAlignment', 'center', 'Color', [0.5 0.5 0.5]);
text(p.draw.panel4Axes, 192, 0.97, 'Phase 2', 'FontSize', 9, ...
    'HorizontalAlignment', 'center', 'Color', [0.5 0.5 0.5]);
text(p.draw.panel4Axes, 320, 0.97, 'Phase 3', 'FontSize', 9, ...
    'HorizontalAlignment', 'center', 'Color', [0.5 0.5 0.5]);

% Create plot objects for cumulative traces
% Phase 1: by hemifield
p.draw.plotObs.cum_p1_left = plot(p.draw.panel4Axes, NaN, NaN, '-', ...
    'Color', highSalLeftColor, 'LineWidth', 1.5);
p.draw.plotObs.cum_p1_right = plot(p.draw.panel4Axes, NaN, NaN, '-', ...
    'Color', highSalRightColor, 'LineWidth', 1.5);

% Phases 2-3: by conflict/congruent
p.draw.plotObs.cum_p23_conflict = plot(p.draw.panel4Axes, NaN, NaN, '-', ...
    'Color', conflictColor, 'LineWidth', 1.5, 'LineStyle', '--');
p.draw.plotObs.cum_p23_congruent = plot(p.draw.panel4Axes, NaN, NaN, '-', ...
    'Color', congruentColor, 'LineWidth', 1.5, 'LineStyle', '--');

legend(p.draw.panel4Axes, ...
    [p.draw.plotObs.cum_p1_left, p.draw.plotObs.cum_p1_right, ...
     p.draw.plotObs.cum_p23_conflict, p.draw.plotObs.cum_p23_congruent], ...
    {'P1: Sal Left', 'P1: Sal Right', 'P2-3: Conflict', 'P2-3: Congruent'}, ...
    'Location', 'southwest', 'FontSize', 8, 'Box', 'off');

%% Panel 5: Session Progress (bottom right)
p.draw.panel5Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.68 0.08 0.28 0.26], ...
    'Visible', 'off');

% Phase progress text
p.draw.phaseText = text(p.draw.panel5Axes, 0.5, 0.85, ...
    'Phase 1/3 (1:1 Ratio)', ...
    'FontSize', 14, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');

% Trial progress text
p.draw.trialText = text(p.draw.panel5Axes, 0.5, 0.65, ...
    'Trial 0/128 in Phase', ...
    'FontSize', 12, 'HorizontalAlignment', 'center');

% Total progress text
p.draw.totalText = text(p.draw.panel5Axes, 0.5, 0.45, ...
    'Total: 0/384', ...
    'FontSize', 12, 'HorizontalAlignment', 'center');

% Session info text
sessionInfoStr = sprintf('Session: %s\nEccentricity: %.1f deg', ...
    p.init.sessionId, p.trVarsInit.targetEccentricityDeg);
text(p.draw.panel5Axes, 0.5, 0.25, sessionInfoStr, ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Color', [0.4 0.4 0.4]);

% Outcome summary (will be updated)
p.draw.outcomeText = text(p.draw.panel5Axes, 0.5, 0.05, ...
    'High Sal: 0 | Low Sal: 0 | Errors: 0', ...
    'FontSize', 9, 'HorizontalAlignment', 'center', 'Color', [0.4 0.4 0.4]);

%% Optional: Gaze vs Time Figure (if wantOnlinePlots is true)
if p.trVarsInit.wantOnlinePlots

    p.draw.gazeVsTimeFig = figure(...
        'Position', [10 800 1200 600], ...
        'Name', 'Conflict Task - Gaze Traces', ...
        'NumberTitle', 'off', ...
        'Color', [1 1 1], ...
        'Visible', 'on', ...
        'NextPlot', 'add');

    % Eye position axes
    p.draw.gazePosPlotAxes = axes(...
        'Parent', p.draw.gazeVsTimeFig, ...
        'Position', [0.06 0.55 0.88 0.38], ...
        'TickDir', 'Out', ...
        'LineWidth', 1, ...
        'NextPlot', 'add', ...
        'Color', 'none');
    ylabel(p.draw.gazePosPlotAxes, 'Eye Position (deg)', 'FontSize', 12);

    % Eye velocity axes
    p.draw.gazeVelPlotAxes = axes(...
        'Parent', p.draw.gazeVsTimeFig, ...
        'Position', [0.06 0.10 0.88 0.38], ...
        'TickDir', 'Out', ...
        'LineWidth', 1, ...
        'NextPlot', 'add', ...
        'Color', 'none', ...
        'YLim', [0 1200]);
    xlabel(p.draw.gazeVelPlotAxes, 'Time from fixation acquisition (s)', 'FontSize', 12);
    ylabel(p.draw.gazeVelPlotAxes, 'Eye Velocity (deg/s)', 'FontSize', 12);

    % Create plot objects
    p.draw.plotObs.xGaze = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0.294 0 0.573], 'LineWidth', 1.5);
    p.draw.plotObs.yGaze = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0 0.424 0.820], 'LineWidth', 1.5);
    p.draw.plotObs.tgt = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0.047 0.482 0.863], 'LineWidth', 1);
    p.draw.plotObs.fix = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0.102 0.522 1.000], 'LineWidth', 1);
    p.draw.plotObs.eyeVel = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        'Color', [0 0 0], 'LineWidth', 1.5);
    p.draw.plotObs.sacOn = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        'Color', [0.882 0.745 0.416], 'LineWidth', 2);
    p.draw.plotObs.sacOff = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        'Color', [0.600 0.310 0], 'LineWidth', 2);
    p.draw.plotObs.vThresh = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        ':', 'LineWidth', 1.5, 'Color', [0.828 0.373 0.718]);

    % Add legends
    legend(p.draw.gazePosPlotAxes, ...
        [p.draw.plotObs.xGaze, p.draw.plotObs.yGaze], ...
        {'Eye X', 'Eye Y'}, 'Location', 'northwest', 'Box', 'off');
    legend(p.draw.gazeVelPlotAxes, ...
        [p.draw.plotObs.eyeVel, p.draw.plotObs.vThresh], ...
        {'Velocity', 'Threshold'}, 'Location', 'northwest', 'Box', 'off');
end

end
