function p = extraWindowSetup(p)
%   p = extraWindowSetup(p)
%
% Initialize plotting windows for the Conflict Task (refactored design).
% Creates a 3x3 panel layout:
%   Row 1: P(High Salience) panels
%     Panel 1: Phase 1 (1:1) by Hemifield
%     Panel 2: Phases 2-3 Conflict vs Congruent
%   Row 2: Median RT panels (corresponding to Row 1)
%     Panel 3: Phase 1 Median RT by Hemifield
%     Panel 4: Phases 2-3 Median RT Conflict vs Congruent
%   Row 3: Choice Evolution (spans 2 columns)
%     Panel 5: Cumulative P(High Salience) over session
%   Column 3: Information panel (spans all 3 rows)
%     Panel 6: Session info, reward parameters, outcome counts

%% Close existing figure if present
tachFigHandle = findall(0, 'Name', 'Conflict Task - Online Visualization');
if ~isempty(tachFigHandle)
    close(tachFigHandle)
end

%% Create new figure
p.draw.vizFig = figure(...
    'Position', [1220 50 1200 950], ...
    'Name', 'Conflict Task - Online Visualization', ...
    'NumberTitle', 'off', ...
    'Color', [1 1 1], ...
    'Visible', 'on', ...
    'NextPlot', 'add');

%% Define colors
highSalLeftColor = [0.850 0.325 0.098];   % Orange for High Salience Left / Conflict
highSalRightColor = [0.000 0.447 0.741];  % Blue for High Salience Right / Congruent
conflictColor = highSalLeftColor;
congruentColor = highSalRightColor;

% Delta-t values for x-axis
deltaTValues = p.status.deltaTValues;  % [-150, 150]

%% ======================== ROW 1: P(High Salience) ========================

%% Panel 1: Phase 1 (1:1) by Hemifield (Row 1, Col 1)
p.draw.panel1Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.06 0.72 0.28 0.22], ...
    'TickDir', 'out', ...
    'LineWidth', 1.5, ...
    'NextPlot', 'add', ...
    'XLim', [-200 200], ...
    'YLim', [0 1], ...
    'XTick', deltaTValues, ...
    'YTick', [0 0.25 0.5 0.75 1], ...
    'FontSize', 10);

xlabel(p.draw.panel1Axes, '\Deltat (ms)', 'FontSize', 11);
ylabel(p.draw.panel1Axes, 'P(High Salience)', 'FontSize', 11);
title(p.draw.panel1Axes, 'Phase 1 - By Hemifield', 'FontSize', 12, 'FontWeight', 'bold');

plot(p.draw.panel1Axes, [-200 200], [0.5 0.5], '--', 'Color', [0.7 0.7 0.7], 'LineWidth', 1);

p.draw.plotObs.p1_highSalLeft = plot(p.draw.panel1Axes, NaN, NaN, '-o', ...
    'Color', highSalLeftColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', highSalLeftColor);
p.draw.plotObs.p1_highSalRight = plot(p.draw.panel1Axes, NaN, NaN, '-o', ...
    'Color', highSalRightColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', highSalRightColor);

legend(p.draw.panel1Axes, ...
    [p.draw.plotObs.p1_highSalLeft, p.draw.plotObs.p1_highSalRight], ...
    {'High Sal LEFT', 'High Sal RIGHT'}, ...
    'Location', 'southeast', 'FontSize', 9, 'Box', 'off');

%% Panel 2: Phases 2-3 Conflict vs Congruent (Row 1, Col 2)
p.draw.panel2Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.40 0.72 0.28 0.22], ...
    'TickDir', 'out', ...
    'LineWidth', 1.5, ...
    'NextPlot', 'add', ...
    'XLim', [-200 200], ...
    'YLim', [0 1], ...
    'XTick', deltaTValues, ...
    'YTick', [0 0.25 0.5 0.75 1], ...
    'FontSize', 10);

xlabel(p.draw.panel2Axes, '\Deltat (ms)', 'FontSize', 11);
ylabel(p.draw.panel2Axes, 'P(High Salience)', 'FontSize', 11);
title(p.draw.panel2Axes, 'Phases 2-3 - Conflict vs Congruent', 'FontSize', 12, 'FontWeight', 'bold');

plot(p.draw.panel2Axes, [-200 200], [0.5 0.5], '--', 'Color', [0.7 0.7 0.7], 'LineWidth', 1);

p.draw.plotObs.p23_conflict = plot(p.draw.panel2Axes, NaN, NaN, '-o', ...
    'Color', conflictColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', conflictColor);
p.draw.plotObs.p23_congruent = plot(p.draw.panel2Axes, NaN, NaN, '-o', ...
    'Color', congruentColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', congruentColor);

legend(p.draw.panel2Axes, ...
    [p.draw.plotObs.p23_conflict, p.draw.plotObs.p23_congruent], ...
    {'Conflict', 'Congruent'}, ...
    'Location', 'southeast', 'FontSize', 9, 'Box', 'off');

%% ======================== ROW 2: Median RT ========================

%% Panel 3: Phase 1 Median RT by Hemifield (Row 2, Col 1)
p.draw.panel3Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.06 0.42 0.28 0.22], ...
    'TickDir', 'out', ...
    'LineWidth', 1.5, ...
    'NextPlot', 'add', ...
    'XLim', [-200 200], ...
    'YLim', [100 500], ...
    'XTick', deltaTValues, ...
    'FontSize', 10);

xlabel(p.draw.panel3Axes, '\Deltat (ms)', 'FontSize', 11);
ylabel(p.draw.panel3Axes, 'Median RT (ms)', 'FontSize', 11);
title(p.draw.panel3Axes, 'Phase 1 - Median RT', 'FontSize', 12, 'FontWeight', 'bold');

p.draw.plotObs.rt_p1_highSalLeft = plot(p.draw.panel3Axes, NaN, NaN, '-s', ...
    'Color', highSalLeftColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', highSalLeftColor);
p.draw.plotObs.rt_p1_highSalRight = plot(p.draw.panel3Axes, NaN, NaN, '-s', ...
    'Color', highSalRightColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', highSalRightColor);

legend(p.draw.panel3Axes, ...
    [p.draw.plotObs.rt_p1_highSalLeft, p.draw.plotObs.rt_p1_highSalRight], ...
    {'High Sal LEFT', 'High Sal RIGHT'}, ...
    'Location', 'northeast', 'FontSize', 9, 'Box', 'off');

%% Panel 4: Phases 2-3 Median RT Conflict vs Congruent (Row 2, Col 2)
p.draw.panel4Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.40 0.42 0.28 0.22], ...
    'TickDir', 'out', ...
    'LineWidth', 1.5, ...
    'NextPlot', 'add', ...
    'XLim', [-200 200], ...
    'YLim', [100 500], ...
    'XTick', deltaTValues, ...
    'FontSize', 10);

xlabel(p.draw.panel4Axes, '\Deltat (ms)', 'FontSize', 11);
ylabel(p.draw.panel4Axes, 'Median RT (ms)', 'FontSize', 11);
title(p.draw.panel4Axes, 'Phases 2-3 - Median RT', 'FontSize', 12, 'FontWeight', 'bold');

p.draw.plotObs.rt_p23_conflict = plot(p.draw.panel4Axes, NaN, NaN, '-s', ...
    'Color', conflictColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', conflictColor);
p.draw.plotObs.rt_p23_congruent = plot(p.draw.panel4Axes, NaN, NaN, '-s', ...
    'Color', congruentColor, 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', congruentColor);

legend(p.draw.panel4Axes, ...
    [p.draw.plotObs.rt_p23_conflict, p.draw.plotObs.rt_p23_congruent], ...
    {'Conflict', 'Congruent'}, ...
    'Location', 'northeast', 'FontSize', 9, 'Box', 'off');

%% ======================== ROW 3: Choice Evolution ========================

%% Panel 5: Cumulative Evolution (Row 3, Cols 1-2)
p.draw.panel5Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.06 0.06 0.62 0.28], ...
    'TickDir', 'out', ...
    'LineWidth', 1.5, ...
    'NextPlot', 'add', ...
    'XLim', [0 460], ...
    'YLim', [0 1], ...
    'YTick', [0 0.25 0.5 0.75 1], ...
    'FontSize', 10);

xlabel(p.draw.panel5Axes, 'Trial Number', 'FontSize', 11);
ylabel(p.draw.panel5Axes, 'Cumulative P(High Salience)', 'FontSize', 11);
title(p.draw.panel5Axes, 'Choice Evolution Over Session', 'FontSize', 12, 'FontWeight', 'bold');

% Reference line at 0.5
plot(p.draw.panel5Axes, [0 460], [0.5 0.5], '--', 'Color', [0.7 0.7 0.7], 'LineWidth', 1);

% Phase transition lines
p.draw.plotObs.phaseLine1 = plot(p.draw.panel5Axes, [192 192], [0 1], ':', ...
    'Color', [0.5 0.5 0.5], 'LineWidth', 1.5);
p.draw.plotObs.phaseLine2 = plot(p.draw.panel5Axes, [320 320], [0 1], ':', ...
    'Color', [0.5 0.5 0.5], 'LineWidth', 1.5);

% Phase labels
text(p.draw.panel5Axes, 96, 0.97, 'Phase 1', 'FontSize', 9, ...
    'HorizontalAlignment', 'center', 'Color', [0.5 0.5 0.5]);
text(p.draw.panel5Axes, 256, 0.97, 'Phase 2', 'FontSize', 9, ...
    'HorizontalAlignment', 'center', 'Color', [0.5 0.5 0.5]);
text(p.draw.panel5Axes, 384, 0.97, 'Phase 3', 'FontSize', 9, ...
    'HorizontalAlignment', 'center', 'Color', [0.5 0.5 0.5]);

% Phase 1: by hemifield
p.draw.plotObs.cum_p1_left = plot(p.draw.panel5Axes, NaN, NaN, '-', ...
    'Color', highSalLeftColor, 'LineWidth', 1.5);
p.draw.plotObs.cum_p1_right = plot(p.draw.panel5Axes, NaN, NaN, '-', ...
    'Color', highSalRightColor, 'LineWidth', 1.5);

% Phases 2-3: by conflict/congruent
p.draw.plotObs.cum_p23_conflict = plot(p.draw.panel5Axes, NaN, NaN, '-', ...
    'Color', conflictColor, 'LineWidth', 1.5, 'LineStyle', '--');
p.draw.plotObs.cum_p23_congruent = plot(p.draw.panel5Axes, NaN, NaN, '-', ...
    'Color', congruentColor, 'LineWidth', 1.5, 'LineStyle', '--');

legend(p.draw.panel5Axes, ...
    [p.draw.plotObs.cum_p1_left, p.draw.plotObs.cum_p1_right, ...
     p.draw.plotObs.cum_p23_conflict, p.draw.plotObs.cum_p23_congruent], ...
    {'P1: Sal Left', 'P1: Sal Right', 'P2-3: Conflict', 'P2-3: Congruent'}, ...
    'Location', 'southwest', 'FontSize', 8, 'Box', 'off');

%% ======================== COLUMN 3: Information Panel ========================

%% Panel 6: Session Info (Col 3, all rows)
p.draw.panel6Axes = axes(...
    'Parent', p.draw.vizFig, ...
    'Position', [0.74 0.06 0.24 0.88], ...
    'Visible', 'off');

% Compute reward values for display
C = p.trVarsInit.rewardDurationMs;
R = p.trVarsInit.rewardRatioBig;
probHigh = p.trVarsInit.rewardProbHigh;
equalR = round(C / 2);
smallR = round(C * 1 / (1 + R));
bigR = round(C * R / (1 + R));

% Section 1: Phase progress
p.draw.phaseText = text(p.draw.panel6Axes, 0.5, 0.95, ...
    'Phase 1/3', ...
    'FontSize', 14, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');

p.draw.trialText = text(p.draw.panel6Axes, 0.5, 0.90, ...
    sprintf('Trial 0/%d in Phase', p.init.trialsPerPhaseList(1)), ...
    'FontSize', 12, 'HorizontalAlignment', 'center');

p.draw.totalText = text(p.draw.panel6Axes, 0.5, 0.85, ...
    sprintf('Total: 0/%d', p.init.totalTrials), ...
    'FontSize', 12, 'HorizontalAlignment', 'center');

% Section 2: Reward parameters (static)
rewardParamStr = {...
    '--- Reward Parameters ---', ...
    sprintf('Budget: %d ms', C), ...
    sprintf('Ratio big:small = %.1f:1', R), ...
    sprintf('Big: %d ms | Small: %d ms', bigR, smallR), ...
    sprintf('Equal: %d ms each', equalR), ...
    sprintf('P(canonical) P2/3: %.0f%%', probHigh * 100)};
text(p.draw.panel6Axes, 0.5, 0.72, rewardParamStr, ...
    'FontSize', 9, 'HorizontalAlignment', 'center', 'Color', [0.3 0.3 0.3]);

% Section 3: Current reward info (dynamic)
p.draw.rewardInfoText = text(p.draw.panel6Axes, 0.5, 0.56, ...
    'BigSide: - | L:- R:-', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Color', [0.1 0.5 0.1]);

% Section 4: Outcome counts (dynamic)
p.draw.outcomeText = text(p.draw.panel6Axes, 0.5, 0.44, ...
    {'--- Outcomes ---', ...
     'High Sal: 0 | Low Sal: 0', ...
     'Fix Breaks: 0', ...
     'No Response: 0', ...
     'Inaccurate: 0'}, ...
    'FontSize', 9, 'HorizontalAlignment', 'center', 'Color', [0.4 0.4 0.4]);

% Section 5: Single-stim counter
p.draw.singleStimText = text(p.draw.panel6Axes, 0.5, 0.28, ...
    'Single-Stim: 0/0 correct', ...
    'FontSize', 10, 'HorizontalAlignment', 'center', 'Color', [0.2 0.6 0.2]);

% Section 6: Session info (static)
sessionInfoStr = {sprintf('Session: %s', p.init.sessionId), ...
    sprintf('Eccentricity: %.1f deg', p.trVarsInit.targetEccentricityDeg)};
text(p.draw.panel6Axes, 0.5, 0.18, sessionInfoStr, ...
    'FontSize', 9, 'HorizontalAlignment', 'center', 'Color', [0.4 0.4 0.4]);

% Section 7: P(HighSal) summary (dynamic)
p.draw.pHighSalSummaryText = text(p.draw.panel6Axes, 0.5, 0.08, ...
    {'--- P(HighSal) ---', 'Overall: - (n=0)'}, ...
    'FontSize', 9, 'HorizontalAlignment', 'center', 'Color', [0.3 0.3 0.6]);

%% Optional: Gaze vs Time Figure (if wantOnlinePlots is true)
if p.trVarsInit.wantOnlinePlots

    p.draw.gazeVsTimeFig = figure(...
        'Position', [10 800 1200 600], ...
        'Name', 'Conflict Task - Gaze Traces', ...
        'NumberTitle', 'off', ...
        'Color', [1 1 1], ...
        'Visible', 'on', ...
        'NextPlot', 'add');

    % Eye position axes
    p.draw.gazePosPlotAxes = axes(...
        'Parent', p.draw.gazeVsTimeFig, ...
        'Position', [0.06 0.55 0.88 0.38], ...
        'TickDir', 'Out', ...
        'LineWidth', 1, ...
        'NextPlot', 'add', ...
        'Color', 'none');
    ylabel(p.draw.gazePosPlotAxes, 'Eye Position (deg)', 'FontSize', 12);

    % Eye velocity axes
    p.draw.gazeVelPlotAxes = axes(...
        'Parent', p.draw.gazeVsTimeFig, ...
        'Position', [0.06 0.10 0.88 0.38], ...
        'TickDir', 'Out', ...
        'LineWidth', 1, ...
        'NextPlot', 'add', ...
        'Color', 'none', ...
        'YLim', [0 1200]);
    xlabel(p.draw.gazeVelPlotAxes, 'Time from fixation acquisition (s)', 'FontSize', 12);
    ylabel(p.draw.gazeVelPlotAxes, 'Eye Velocity (deg/s)', 'FontSize', 12);

    % Create plot objects
    p.draw.plotObs.xGaze = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0.294 0 0.573], 'LineWidth', 1.5);
    p.draw.plotObs.yGaze = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0 0.424 0.820], 'LineWidth', 1.5);
    p.draw.plotObs.tgt = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0.047 0.482 0.863], 'LineWidth', 1);
    p.draw.plotObs.fix = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
        'Color', [0.102 0.522 1.000], 'LineWidth', 1);
    p.draw.plotObs.eyeVel = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        'Color', [0 0 0], 'LineWidth', 1.5);
    p.draw.plotObs.sacOn = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        'Color', [0.882 0.745 0.416], 'LineWidth', 2);
    p.draw.plotObs.sacOff = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        'Color', [0.600 0.310 0], 'LineWidth', 2);
    p.draw.plotObs.vThresh = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
        ':', 'LineWidth', 1.5, 'Color', [0.828 0.373 0.718]);

    % Add legends
    legend(p.draw.gazePosPlotAxes, ...
        [p.draw.plotObs.xGaze, p.draw.plotObs.yGaze], ...
        {'Eye X', 'Eye Y'}, 'Location', 'northwest', 'Box', 'off');
    legend(p.draw.gazeVelPlotAxes, ...
        [p.draw.plotObs.eyeVel, p.draw.plotObs.vThresh], ...
        {'Velocity', 'Threshold'}, 'Location', 'northwest', 'Box', 'off');
end

end
