function p = plotWindowSetup(p)
%PLOTWINDOWSETUP Create the SRS online behavioral dashboard.
%
% Behavioral plots contain successful trials only. The status panel is
% refreshed after every attempt. A tiled layout is used so titles, labels,
% and legends keep their own space when the window is resized.

%% Initialize online behavioral storage
p.status.onlinePlot = struct( ...
    'trial',                    [], ... % good-trial index
    'attemptTrial',             [], ... % absolute attempted-trial index
    'trialType',                [], ... % 1=congruent, 2=conflict
    'nStim',                    [], ... % 1=instruction, 2=choice
    'mappingValid',             [], ...
    'choseHighSal',             [], ...
    'choseHighReward',          [], ...
    'rtMs',                     [], ...
    'chosenTargetID',           [], ...
    'chosenRewardMs',           [], ...
    'previousRewardMs',         [], ...
    'previousTrialType',        [], ...
    'previousChoseHighReward',  [], ...
    'previousChoseHighSalience',[], ...
    'switchedTarget',           []);

%% Create window
oldWin = findobj('Name', 'OnlinePlotWindow');
if ~isempty(oldWin)
    delete(oldWin);
end

p.draw.onlinePlotWindow = figure( ...
    'Position', [900 40 1500 1120], ...
    'Name', 'OnlinePlotWindow', ...
    'NumberTitle', 'off', ...
    'Color', [1 1 1], ...
    'Visible', 'off', ...
    'NextPlot', 'add');

if ~isfield(p.trVarsInit, 'wantOnlinePlots') || ...
        ~p.trVarsInit.wantOnlinePlots
    return;
end

% Plot panel and status panel are separated so axes labels cannot overlap
% the status listbox.
p.draw.onlinePlotPanel = uipanel( ...
    'Parent', p.draw.onlinePlotWindow, ...
    'Units', 'normalized', ...
    'Position', [0.01 0.01 0.73 0.98], ...
    'BorderType', 'none', ...
    'BackgroundColor', [1 1 1]);

p.draw.onlinePlotLayout = tiledlayout( ...
    p.draw.onlinePlotPanel, 6, 6, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

%% Reward difference
p.draw.onlinePlotAxes.rewardDiff = nexttile( ...
    p.draw.onlinePlotLayout, [1 6]);
formatAxis(p.draw.onlinePlotAxes.rewardDiff, ...
    'Reward difference', 'Successful trial', 'T1 - T2 reward (ms)');
p.draw.onlinePlotObj.rewardZero = plot( ...
    p.draw.onlinePlotAxes.rewardDiff, [0 10], [0 0], ':k', ...
    'LineWidth', 1.1);
p.draw.onlinePlotObj.rewardDiff = plot( ...
    p.draw.onlinePlotAxes.rewardDiff, NaN, NaN, '-', ...
    'Marker', '.', 'MarkerSize', 9, ...
    'Color', [0.00 0.45 0.74], 'LineWidth', 1.3);
text(p.draw.onlinePlotAxes.rewardDiff, 0.01, 0.88, ...
    '+ T1 richer / - T2 richer', 'Units', 'normalized', 'FontSize', 8);
set(p.draw.onlinePlotAxes.rewardDiff, 'XLim', [0 10], 'YLim', [-200 200]);

%% Luminance difference
p.draw.onlinePlotAxes.luminanceDiff = nexttile( ...
    p.draw.onlinePlotLayout, [1 6]);
formatAxis(p.draw.onlinePlotAxes.luminanceDiff, ...
    'Measured luminance difference', 'Successful trial', ...
    'T1 - T2 luminance (cd/m^2)');
p.draw.onlinePlotObj.luminanceZero = plot( ...
    p.draw.onlinePlotAxes.luminanceDiff, [0 10], [0 0], ':k', ...
    'LineWidth', 1.1);
p.draw.onlinePlotObj.luminanceDiff = plot( ...
    p.draw.onlinePlotAxes.luminanceDiff, NaN, NaN, '-', ...
    'Marker', '.', 'MarkerSize', 9, ...
    'Color', [0.47 0.67 0.19], 'LineWidth', 1.3);
text(p.draw.onlinePlotAxes.luminanceDiff, 0.01, 0.88, ...
    '+ T1 brighter / - T2 brighter', ...
    'Units', 'normalized', 'FontSize', 8);
set(p.draw.onlinePlotAxes.luminanceDiff, 'XLim', [0 10], 'YLim', [-13 13]);

%% DKL hue-contrast difference
p.draw.onlinePlotAxes.hueContrastDiff = nexttile( ...
    p.draw.onlinePlotLayout, [1 6]);
formatAxis(p.draw.onlinePlotAxes.hueContrastDiff, ...
    'DKL hue-contrast difference', 'Successful trial', ...
    'T1 - T2 distance from background (deg)');
p.draw.onlinePlotObj.hueContrastZero = plot( ...
    p.draw.onlinePlotAxes.hueContrastDiff, [0 10], [0 0], ':k', ...
    'LineWidth', 1.1);
p.draw.onlinePlotObj.hueContrastDiff = plot( ...
    p.draw.onlinePlotAxes.hueContrastDiff, NaN, NaN, '-', ...
    'Marker', '.', 'MarkerSize', 9, ...
    'Color', [0.49 0.18 0.56], 'LineWidth', 1.3);
text(p.draw.onlinePlotAxes.hueContrastDiff, 0.01, 0.88, ...
    '+ T1 more contrasted / - T2 more contrasted', ...
    'Units', 'normalized', 'FontSize', 8);
set(p.draw.onlinePlotAxes.hueContrastDiff, ...
    'XLim', [0 10], 'YLim', [-180 180]);

%% Conflict choices: the two bars must sum to one
p.draw.onlinePlotAxes.conflictChoice = nexttile( ...
    p.draw.onlinePlotLayout, [1 2]);
formatCategoryAxis(p.draw.onlinePlotAxes.conflictChoice, ...
    'Conflict choices', {'High reward', 'High salience'});
p.draw.onlinePlotObj.conflictChoiceChance = plot( ...
    p.draw.onlinePlotAxes.conflictChoice, [0.5 2.5], [0.5 0.5], '--', ...
    'Color', 0.75 * [1 1 1], 'LineWidth', 1.0);
p.draw.onlinePlotObj.conflictChoiceHighReward = bar( ...
    p.draw.onlinePlotAxes.conflictChoice, 1, NaN, 0.55, ...
    'FaceColor', [0 0 1], 'EdgeColor', 'none');
p.draw.onlinePlotObj.conflictChoiceHighSalience = bar( ...
    p.draw.onlinePlotAxes.conflictChoice, 2, NaN, 0.55, ...
    'FaceColor', [1 0 0], 'EdgeColor', 'none');

%% Congruent choices: favored and unfavored are complementary
p.draw.onlinePlotAxes.congruentChoice = nexttile( ...
    p.draw.onlinePlotLayout, [1 2]);
formatCategoryAxis(p.draw.onlinePlotAxes.congruentChoice, ...
    'Congruent choices', {'Favored HR=HS', 'Unfavored'});
p.draw.onlinePlotObj.congruentChoiceChance = plot( ...
    p.draw.onlinePlotAxes.congruentChoice, [0.5 2.5], [0.5 0.5], '--', ...
    'Color', 0.75 * [1 1 1], 'LineWidth', 1.0);
p.draw.onlinePlotObj.congruentChoiceFavored = bar( ...
    p.draw.onlinePlotAxes.congruentChoice, 1, NaN, 0.55, ...
    'FaceColor', [0 0 1], 'EdgeColor', 'none');
p.draw.onlinePlotObj.congruentChoiceUnfavored = bar( ...
    p.draw.onlinePlotAxes.congruentChoice, 2, NaN, 0.55, ...
    'FaceColor', [1 0 0], 'EdgeColor', 'none');

%% Median RT split by conflict decision
p.draw.onlinePlotAxes.medianRT = nexttile( ...
    p.draw.onlinePlotLayout, [1 2]);
formatThreeCategoryAxis(p.draw.onlinePlotAxes.medianRT, ...
    'Median RT by choice', {'Conf-HR', 'Conf-HS', 'Congruent'}, ...
    'RT (ms)');
set(p.draw.onlinePlotAxes.medianRT, 'YLim', [0 500]);
p.draw.onlinePlotObj.medianRTConflictHighReward = bar( ...
    p.draw.onlinePlotAxes.medianRT, 1, NaN, 0.55, ...
    'FaceColor', [0.00 0.45 0.74], 'EdgeColor', 'none');
p.draw.onlinePlotObj.medianRTConflictHighSalience = bar( ...
    p.draw.onlinePlotAxes.medianRT, 2, NaN, 0.55, ...
    'FaceColor', [0.85 0.33 0.10], 'EdgeColor', 'none');
p.draw.onlinePlotObj.medianRTCongruent = bar( ...
    p.draw.onlinePlotAxes.medianRT, 3, NaN, 0.55, ...
    'FaceColor', [0.47 0.67 0.19], 'EdgeColor', 'none');

%% Exploration: previous reward and previous decision category
p.draw.onlinePlotAxes.exploration = nexttile( ...
    p.draw.onlinePlotLayout, [1 3]);
formatAxis(p.draw.onlinePlotAxes.exploration, ...
    'Switching vs reward on previous choice', ...
    'Previous chosen reward (ms)', 'Stay / switch identity');
set(p.draw.onlinePlotAxes.exploration, ...
    'YLim', [-0.12 1.12], ...
    'YTick', [0 1], ...
    'YTickLabel', {'Stay', 'Switch'});
p.draw.onlinePlotObj.explorationChance = plot( ...
    p.draw.onlinePlotAxes.exploration, [0 1], [0.5 0.5], '--', ...
    'Color', 0.82 * [1 1 1], 'LineWidth', 1.0);

% Raw transitions are colored by the previous successful choice category.
p.draw.onlinePlotObj.exploreRawPrevCongruent = plot( ...
    p.draw.onlinePlotAxes.exploration, NaN, NaN, 'o', ...
    'LineStyle', 'none', 'MarkerSize', 4, ...
    'MarkerEdgeColor', [0.40 0.40 0.40]);
p.draw.onlinePlotObj.exploreRawPrevConflictHR = plot( ...
    p.draw.onlinePlotAxes.exploration, NaN, NaN, 'o', ...
    'LineStyle', 'none', 'MarkerSize', 4, ...
    'MarkerEdgeColor', [0.00 0.45 0.74]);
p.draw.onlinePlotObj.exploreRawPrevConflictHS = plot( ...
    p.draw.onlinePlotAxes.exploration, NaN, NaN, 'o', ...
    'LineStyle', 'none', 'MarkerSize', 4, ...
    'MarkerEdgeColor', [0.85 0.33 0.10]);

p.draw.onlinePlotObj.exploreBinPrevCongruent = plot( ...
    p.draw.onlinePlotAxes.exploration, NaN, NaN, '-o', ...
    'Color', [0.35 0.35 0.35], 'LineWidth', 1.7, 'MarkerSize', 5, ...
    'MarkerFaceColor', [0.35 0.35 0.35]);
p.draw.onlinePlotObj.exploreBinPrevConflictHR = plot( ...
    p.draw.onlinePlotAxes.exploration, NaN, NaN, '-o', ...
    'Color', [0.00 0.45 0.74], 'LineWidth', 1.7, 'MarkerSize', 5, ...
    'MarkerFaceColor', [0.00 0.45 0.74]);
p.draw.onlinePlotObj.exploreBinPrevConflictHS = plot( ...
    p.draw.onlinePlotAxes.exploration, NaN, NaN, '-o', ...
    'Color', [0.85 0.33 0.10], 'LineWidth', 1.7, 'MarkerSize', 5, ...
    'MarkerFaceColor', [0.85 0.33 0.10]);
legend(p.draw.onlinePlotAxes.exploration, ...
    [p.draw.onlinePlotObj.exploreBinPrevCongruent, ...
     p.draw.onlinePlotObj.exploreBinPrevConflictHR, ...
     p.draw.onlinePlotObj.exploreBinPrevConflictHS], ...
    {'Prev congruent', 'Prev conflict-HR', 'Prev conflict-HS'}, ...
    'Location', 'northwest', 'FontSize', 7);

%% Exploration transition summary
p.draw.onlinePlotAxes.explorationTransition = nexttile( ...
    p.draw.onlinePlotLayout, [1 3]);
formatNineCategoryAxis(p.draw.onlinePlotAxes.explorationTransition, ...
    'P(switch) by transition', ...
    {'Cg>Cg', 'Cg>HR', 'Cg>HS', ...
     'HR>Cg', 'HR>HR', 'HR>HS', ...
     'HS>Cg', 'HS>HR', 'HS>HS'});
p.draw.onlinePlotObj.explorationTransitionChance = plot( ...
    p.draw.onlinePlotAxes.explorationTransition, [0.5 9.5], [0.5 0.5], '--', ...
    'Color', 0.80 * [1 1 1], 'LineWidth', 1.0);
transitionColors = [ ...
    repmat([0.45 0.45 0.45], 3, 1); ...
    repmat([0.00 0.45 0.74], 3, 1); ...
    repmat([0.85 0.33 0.10], 3, 1)];
for iTransition = 1:9
    p.draw.onlinePlotObj.explorationTransitionBars(iTransition) = bar( ...
        p.draw.onlinePlotAxes.explorationTransition, ...
        iTransition, NaN, 0.72, ...
        'FaceColor', transitionColors(iTransition, :), ...
        'EdgeColor', 'none');
end
xtickangle(p.draw.onlinePlotAxes.explorationTransition, 45);

%% Choice evolution
p.draw.onlinePlotAxes.choiceEvolution = nexttile( ...
    p.draw.onlinePlotLayout, [1 6]);
formatAxis(p.draw.onlinePlotAxes.choiceEvolution, ...
    'Choice evolution', 'Successful two-target choice', ...
    'Cumulative P(High salience)');
set(p.draw.onlinePlotAxes.choiceEvolution, 'XLim', [0 10], 'YLim', [0 1]);
p.draw.onlinePlotObj.choiceChance = plot( ...
    p.draw.onlinePlotAxes.choiceEvolution, [0 10], [0.5 0.5], '--', ...
    'Color', 0.80 * [1 1 1], 'LineWidth', 1.0);
p.draw.onlinePlotObj.choiceConflict = plot( ...
    p.draw.onlinePlotAxes.choiceEvolution, NaN, NaN, '-', ...
    'Color', [0.85 0.33 0.10], 'LineWidth', 1.8);
p.draw.onlinePlotObj.choiceCongruent = plot( ...
    p.draw.onlinePlotAxes.choiceEvolution, NaN, NaN, '-', ...
    'Color', [0.00 0.45 0.74], 'LineWidth', 1.8);
p.draw.onlinePlotObj.choiceOverall = plot( ...
    p.draw.onlinePlotAxes.choiceEvolution, NaN, NaN, '--', ...
    'Color', [0.20 0.20 0.20], 'LineWidth', 1.3);
legend(p.draw.onlinePlotAxes.choiceEvolution, ...
    [p.draw.onlinePlotObj.choiceConflict, ...
     p.draw.onlinePlotObj.choiceCongruent, ...
     p.draw.onlinePlotObj.choiceOverall], ...
    {'Conflict', 'Congruent', 'Overall'}, ...
    'Location', 'northeast', 'Orientation', 'horizontal', 'FontSize', 8);

%% Status panel
p.draw.onlinePlotObj.statusText = uicontrol( ...
    'Parent', p.draw.onlinePlotWindow, ...
    'Style', 'listbox', ...
    'Units', 'normalized', ...
    'Position', [0.75 0.01 0.245 0.98], ...
    'BackgroundColor', [0.97 0.97 0.97], ...
    'ForegroundColor', [0 0 0], ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'FixedWidth', ...
    'FontSize', 9, ...
    'String', {'Status will appear here'});

set(p.draw.onlinePlotWindow, 'Visible', 'on');

end

function formatAxis(ax, titleText, xLabelText, yLabelText)
hold(ax, 'on');
box(ax, 'off');
set(ax, 'TickDir', 'out', 'LineWidth', 1, ...
    'XColor', [0 0 0], 'YColor', [0 0 0]);
title(ax, titleText, 'FontSize', 10, 'FontWeight', 'bold', ...
    'Interpreter', 'none');
xlabel(ax, xLabelText, 'FontSize', 8.5, 'Interpreter', 'none');
ylabel(ax, yLabelText, 'FontSize', 8.5, 'Interpreter', 'none');
end

function formatCategoryAxis(ax, titleText, tickLabels)
formatAxis(ax, titleText, '', 'Choice probability');
set(ax, 'XLim', [0.5 2.5], 'YLim', [0 1], ...
    'XTick', 1:2, 'XTickLabel', tickLabels, 'FontSize', 8);
end

function formatThreeCategoryAxis(ax, titleText, tickLabels, yLabelText)
formatAxis(ax, titleText, '', yLabelText);
set(ax, 'XLim', [0.5 3.5], 'XTick', 1:3, ...
    'XTickLabel', tickLabels, 'FontSize', 8);
end

function formatNineCategoryAxis(ax, titleText, tickLabels)
formatAxis(ax, titleText, '', 'P(switch)');
set(ax, 'XLim', [0.5 9.5], 'YLim', [0 1], ...
    'XTick', 1:9, 'XTickLabel', tickLabels, 'FontSize', 6.5);
end
