function p = srsMoving_init(p)
%SRSMOVING_INIT Initialize the moving-target SRS variant.

% Shared SRS initialization opens the display, builds the schedule, creates
% online plots and loads p.init.codes from +pds/initCodes.m.
p = srsSmooth_init(p);

requiredCodes = { ...
    'uniqueTaskCode_SRS_mooving', ...
    'movingT1Angle_x10', ...
    'movingT2Angle_x10', ...
    'movingSeparation_x10', ...
    'movingEccentricity_x100', ...
    'T1PhysicalSide', ...
    'T2PhysicalSide', ...
    'chosenPhysicalSide', ...
    'movingTargetsStraddleLR', ...
    'movingTargetsStraddleUD', ...
    'chosenHorizontalRank', ...
    'chosenVerticalRank'};

missing = requiredCodes(~isfield(p.init.codes, requiredCodes));
if ~isempty(missing)
    error('SRS_mooving:MissingInitCodes', ...
        ['Your +pds/initCodes.m is not the SRS_mooving version. Missing: ', ...
         '%s. Replace +pds/initCodes.m before running this task.'], ...
        strjoin(missing, ', '));
end

% Give this variant a unique ephys task identifier rather than reusing the
% fixed-location SRS task code.
p.init.taskCode = p.init.codes.uniqueTaskCode_SRS_mooving;

% Fail immediately if any paired-strobe code in this task does not exist.
strobeNames = p.init.strobeList(:,1);
missingStrobes = strobeNames(~isfield(p.init.codes, strobeNames));
if ~isempty(missingStrobes)
    error('SRS_mooving:MissingStrobeCodes', ...
        'Missing paired-strobe code(s): %s', strjoin(missingStrobes, ', '));
end

end
