function inWindowLogical = eyeInWindow(p, whichWinString, varargin)
%
% inWindowLogical = eyeInWindow(p, ['target' / 'fixation'])
%
% Checks whether the current eye positions is within the 'target' or
% 'fixation' window. Returns "true" if the eye is in the window or if
% "passEye" is set to "true".


% if no argument was passed to say whether we're checking relative to
% target or fixation, assume we're checking relative to fixation.
if nargin < 2
    whichWinString = 'fixation';
elseif nargin > 2
    targRow = varargin{1}; % first input for varargin should be the specified "N" of targetN
end

% check "in-window-ness" appropriately
switch whichWinString
    case 'fixation'
        inWindowLogical = ...
            (abs(p.trVars.eyeDegX - p.trVars.fixDegX) < ...
            p.trVars.fixWinWidthDeg && ...
            abs(p.trVars.eyeDegY - p.trVars.fixDegY) < ...
            p.trVars.fixWinHeightDeg) || p.trVars.passEye;
    
    case 'target'
        inWindowLogical = ...
            (abs(p.trVars.eyeDegX - p.trVars.targDegX) < ...
            p.trVars.targWinWidthDeg && ...
            abs(p.trVars.eyeDegY - p.trVars.targDegY) < ...
            p.trVars.targWinHeightDeg) || p.trVars.passEye;
        
    case 'image'
      inWindowLogical = ...
          (abs(p.trVars.eyeDegX - p.trVars.fixDegX) < ...
          p.trVars.imageWinWidthDeg && ...
            abs(p.trVars.eyeDegY - p.trVars.fixDegY) < ...
            p.trVars.imageWinHeightDeg) || p.trVars.passEye;
            
% for targetN, p.trVars.NdegX and p.trVars.NdegY contain a list of target 
% window centers (x-coordinates and y-coordinates, respectively).
    case 'targetN'
      inWindowLogical = ...
          (abs(p.trVars.eyeDegX - p.trVars.targNdegX(targRow)) < ...
          p.trVars.targWinWidthDeg && ...
            abs(p.trVars.eyeDegY - p.trVars.targNdegY(targRow)) < ...
            p.trVars.targWinHeightDeg) || p.trVars.passEye;
        
end

end
