function varargout = heatMapPlotGUI(varargin)

% Declare non-UI data so that they can be used in any functions in this GUI
% file, including functions triggered by creating the GUI layout below
mOutputArgs = {};  % Variable for storing output when GUI returns

% Build main figure & plotting axes
hMainFigure         =   figure(...       % the main GUI figure
    'MenuBar', 'none', ...
    'Toolbar', 'none', ...
    'HandleVisibility', 'callback', ...
    'Name', 'Heatmap GUI', ...
    'NumberTitle', 'off', ...
    'Color', get(0, 'defaultuicontrolbackgroundcolor'), ...
    'Position', [0 0 600 800], ...
    'NextPlot', 'Add');

hPlotAxes           =   axes(...         % HeatMap plot axes
    'Tag', 'hPlotAxes', ...
    'Parent', hMainFigure, ...
    'Units', 'normalized', ...
    'HandleVisibility', 'callback', ...
    'Position', [0.05 0.455 0.63 0.525], ...
    'CLim', [0 1], ...
    'CLimMode', 'manual', ...
    'FontSize', 14, ...
    'TickDir', 'Out', ...
    'TickLength', [0.005 0.025], ...
    'LineWIdth', 1, ...
    'NextPlot', 'Add', ...
    'ButtonDownFcn', {@hPlotAxes_ButtonDownFcn, hMainFigure});

hColorBarAxes       =   axes(...         % HeatMap colorbar axes
    'Tag', 'hColorBarAxes', ...
    'Parent', hMainFigure, ...
    'Units', 'normalized', ...
    'HandleVisibility', 'callback', ...
    'Position', [0.69 0.455 0.035 0.525], ...
    'CLim', [0 1], ...
    'CLimMode', 'manual', ...
    'FontSize', 14, ...
    'TickDir', 'Out', ...
    'TickLength', [0.005 0.025], ...
    'LineWIdth', 1, ...
    'NextPlot', 'Add', ...
    'XTickLabel', [], ...
    'YAxisLocation', 'right');

hSpikeAxes1         =   axes(...         % spike plot axes 1
    'Tag', 'hSpikeAxes1', ...
    'Parent', hMainFigure, ...
    'Units', 'normalized', ...
    'HandleVisibility', 'callback', ...
    'Position', [0.05 0.03 0.45 0.175], ...
    'FontSize', 14, ...
    'TickDir', 'Out', ...
    'TickLength', [0.005 0.025], ...
    'LineWIdth', 1, ...
    'NextPlot', 'Add', ...
    'YDir', 'rev', ...
    'YLim', [0 40]);

hSpikeAxes1b        =   axes(...         % spike plot axes 1 - SMOOTH
    'Tag', 'hSpikeAxes1b', ...
    'Parent', hMainFigure, ...
    'Units', 'normalized', ...
    'HandleVisibility', 'callback', ...
    'Position', get(hSpikeAxes1,'Position'), ...
    'FontSize', 14, ...
    'TickDir', 'Out', ...
    'TickLength', [0.005 0.025], ...
    'LineWIdth', 1, ...
    'NextPlot', 'Add', ...
    'Color', 'None', ...
    'YColor', [1 0 0], ...
    'YAxisLocation','right', ...
    'XAxisLocation', 'Top', ...
    'XTick', []);

hSpikeAxes2         =   axes(...         % spike plot axes 2
    'Tag', 'hSpikeAxes2', ...
    'Parent', hMainFigure, ...
    'Units', 'normalized', ...
    'HandleVisibility', 'callback', ...
    'Position', [0.05 0.235 0.45 0.175], ...
    'FontSize', 14, ...
    'TickDir', 'Out', ...
    'TickLength', [0.005 0.025], ...
    'LineWIdth', 1, ...
    'NextPlot', 'Add', ...
    'YDir', 'rev', ...
    'YLim', [0 40]);

hSpikeAxes2b        =   axes(...         % spike plot axes 2 - SMOOTH
    'Tag', 'hSpikeAxes2b', ...
    'Parent', hMainFigure, ...
    'Units', 'normalized', ...
    'HandleVisibility', 'callback', ...
    'Position', get(hSpikeAxes2,'Position'), ...
    'FontSize', 14, ...
    'TickDir', 'Out', ...
    'TickLength', [0.005 0.025], ...
    'LineWIdth', 1, ...
    'NextPlot', 'Add', ...
    'Color', 'None', ...
    'YColor', [1 0 0], ...
    'YAxisLocation','right', ...
    'XAxisLocation', 'Top', ...
    'XTick', []);

hSpikeAxes3         =   axes(...         % spike plot axes 3
    'Tag', 'hSpikeAxes3', ...
    'Parent', hMainFigure, ...
    'Units', 'normalized', ...
    'HandleVisibility', 'callback', ...
    'Position', [0.55 0.235 0.425 0.175], ...
    'FontSize', 14, ...
    'TickDir', 'Out', ...
    'TickLength', [0.005 0.025], ...
    'LineWIdth', 1, ...
    'NextPlot', 'Add', ...
    'YDir', 'rev', ...
    'YLim', [0 40]);

hSpikeAxes3b        =   axes(...         % spike plot axes 3 - SMOOTH
    'Tag', 'hSpikeAxes3b', ...
    'Parent', hMainFigure, ...
    'Units', 'normalized', ...
    'HandleVisibility', 'callback', ...
    'Position', get(hSpikeAxes3,'Position'), ...
    'FontSize', 14, ...
    'TickDir', 'Out', ...
    'TickLength', [0.005 0.025], ...
    'LineWIdth', 1, ...
    'NextPlot', 'Add', ...
    'Color', 'None', ...
    'YColor', [1 0 0], ...
    'YAxisLocation','right', ...
    'XAxisLocation', 'Top', ...
    'XTick', []);

% add lines indicating event timing to spike plotting axes
plot(hSpikeAxes1, [0 0], [0 40], 'b')
plot(hSpikeAxes2, [0 0], [0 40], 'b')
plot(hSpikeAxes3, [0 0], [0 40], 'b')

% add plot objects to secondary spike plotting axes so that as we calculate
% across-trial binned averages, we can just update the x/y data of these
% existing plot objects.
hBindSpikes1        = plot(hSpikeAxes1b, NaN, NaN, 'r', 'LineWidth', 2);
hBindSpikes2        = plot(hSpikeAxes2b, NaN, NaN, 'r', 'LineWidth', 2);
hBindSpikes3        = plot(hSpikeAxes3b, NaN, NaN, 'r', 'LineWidth', 2);

% create an object to store data, this will let us monitor the object's
% properties for changes to trigger function calls.
dataStruct          = makeDataStruct;

% an empty heatmap with default degree limits / divisions-per-degree
hmXLims             = [-30, 30];
hmYLims             = [-20, 20];
divPerDeg           = 0.5;
hTemp               = buildHeatMap(hmXLims, hmYLims, divPerDeg, hPlotAxes, hColorBarAxes);

% store the initial list of target locations (tiling the area).
dataStruct          = initTargetLocs(dataStruct);
nPts                = size(dataStruct.X_Y_Complete,1);

% target locations plot objects. first create an "unvisited target
% location" plot object. We'll hold on to this so that if/when the user
% adds new target locations, they retain the "unvisited" appearance. Also
% create a saccade endpoint graphics object for each target location, and a
% connecting line for them.
hTargetLocUnvis     = plot(hPlotAxes, NaN, NaN, 'ko', 'LineWidth',2, 'MarkerSize', 12, 'ButtonDownFcn', {@hTargetLoc_ButtonDownFcn, dataStruct});
hSacEndLoc          = plot(hPlotAxes, NaN, NaN, 'ks', 'LineWidth',2,'HitTest','off');
hTargSacConLine     = plot(hPlotAxes, NaN(1,2), NaN(1,2), 'k','HitTest','off');
hTargetLocs         = copyobj(hTargetLocUnvis, repmat(hPlotAxes, nPts, 1));
hSacEndLocs         = copyobj(hSacEndLoc, repmat(hPlotAxes, nPts, 1));
hTargSacConLines    = copyobj(hTargSacConLine, repmat(hPlotAxes, nPts, 1));

% Put some dummy data in the structure to plot the heatmap, IF no PDS has
% been supplied as input.
if nargin == 0
    dataStruct                  = dummyPDS(dataStruct);
else
    dataStruct.PDS = varargin{1};
end

addlistener(dataStruct, 'PDS', 'PostSet', @(i1,i2)updatePlots(i1,i2,dataStruct));
addlistener(dataStruct, 'PDS', 'PostSet', @(i1,i2)hTrialMarkersMenu_CreateFcn(i1,i2,dataStruct));
addlistener(dataStruct, 'X_Y_Complete', 'PostSet', @(i1,i2)updateTargetsPlot(i1,i2,dataStruct));
addlistener(dataStruct, 'rfFit', 'PostSet', @(i1,i2)updateFit(i1,i2,dataStruct));

% make a gui-panel to contain the controls for selecting the time-window to
% for selecting spikes to base the heatmap on.
dataStruct          = makeTimingPanel(dataStruct, hMainFigure);

% make a gui-panel to store controls for modifying heatmap properties
% (limits, resolution, ...)
dataStruct          = makeHeatMapPropsPanel(dataStruct, hMainFigure, [divPerDeg, hmXLims, hmYLims]);

% make a gui-panel to contain information / controls for the fit
dataStruct          = makeFitPropsPanel(dataStruct, hMainFigure);

% make a control to change between spike-count mapping and peak-velocity
% mappting
dataStruct          = makeMapTypeButton(dataStruct, hMainFigure);

% make a gui-panel to store controls selecting the target location
dataStruct          = makeTargetSelectPanel(dataStruct, hMainFigure);

% make a gui-panel to store controls for saving the figure
dataStruct          = makeFigureSavePanel(dataStruct, hMainFigure);

% make a gui-panel to store controls for loading a pre-existing peak
% velocity heatmap
dataStruct          = makePkVMapLoadPanel(dataStruct, hMainFigure);

% create an empty raster-line object. it doesn't matter where this lives so
% we're going to put it into the heatmap plot for convenience.
hRasterLine         = plot(hPlotAxes, NaN(2,1),NaN(2,1),'Color',[0 0 0],'LineWidth',1);

% store various object handles in dataStruct
dataStruct.handles.hPlotAx  = hPlotAxes;
dataStruct.handles.hColBrAx = hColorBarAxes;
dataStruct.handles.hSpAx1   = hSpikeAxes1;
dataStruct.handles.hSpAx2   = hSpikeAxes2;
dataStruct.handles.hSpAx3   = hSpikeAxes3;
dataStruct.handles.hSpAx1b  = hSpikeAxes1b;
dataStruct.handles.hSpAx2b  = hSpikeAxes2b;
dataStruct.handles.hSpAx3b  = hSpikeAxes3b;
dataStruct.handles.hUnvisT  = hTargetLocUnvis;
dataStruct.handles.hTPlots  = hTargetLocs;
dataStruct.handles.hScPlt   = hSacEndLoc;
dataStruct.handles.hScPlts  = hSacEndLocs;
dataStruct.handles.hSTCL    = hTargSacConLine;
dataStruct.handles.hSTCLs   = hTargSacConLines;
dataStruct.handles.hHtMp    = hTemp(1);
dataStruct.handles.hCntr    = hTemp(2);
dataStruct.handles.hColrBar = hTemp(3);
dataStruct.handles.hRst     = hRasterLine;
dataStruct.handles.hBSPlt1  = hBindSpikes1;
dataStruct.handles.hBSPlt2  = hBindSpikes2;
dataStruct.handles.hBSPlt3  = hBindSpikes3;

% initial update to heatmap plot
updateHeatMap([], [], dataStruct);

% initial update to target locations plot
updateTargetsPlot([], [], dataStruct);

% update 'UserData' field with populated data structure.
set(hMainFigure, 'UserData', dataStruct);

% Define default output and return it if it is requested by users
mOutputArgs = {hMainFigure, dataStruct};

if nargout>0
    [varargout{1:nargout}] = mOutputArgs{1:nargout};
end

set(hMainFigure, 'Position', [2561        1441        1600        1178]);
%set(hMainFigure, 'Position', [57           5        1287         720]);

end

%%%% Define callback functions
function hPlotAxes_ButtonDownFcn(hObject, eventdata, GUIfig)
% This function is used to grab user-input. A user clicks on this graph if
% they want to add points to the list of saccade targets. That list is
% stored in one field of the 'UserData' field of the GUI figure. This is
% why we have the 'GUIfig' argument to this function, so we can easily pass
% the figure handle.

% Grab data structure
dataStruct                          = get(GUIfig, 'UserData');

% grab last-clicked point
clickedPt                           = get(hObject, 'CurrentPoint');

% update list of targets: (1) find not-yet-completed targets, (2) increment
% their "order", (3) add the new point, placing it first in the "order".
dataStruct.X_Y_Complete             = [[clickedPt(1,1:2), 0, NaN, NaN]; dataStruct.X_Y_Complete];

% update data structure
set(GUIfig, 'UserData', dataStruct);
end

function hTimeWindow_Callback(hObject, eventdata)

newVal = str2double(get(hObject, 'String'));

if ~isempty(newVal)
    set(hObject, 'Value', newVal);
    updateHeatMap([], [], get(get(get(hObject, 'Parent'), 'Parent'), 'UserData'));
else
    set(hObject, 'String', num2str(get(hObject, 'Value')));
end

end

function hTrialMarkersMenu_Callback(hObject, eventdata)
updateHeatMap([], [], get(get(get(hObject, 'Parent'), 'Parent'), 'UserData'));
end

function HeatMapProps_Callback(hObject, eventdata, dataStruct)

% return a list of the panel's children so we have all the values we need.
pKids = get(dataStruct.handles.hHMPanel, 'Children');

% make a list of the tags for each of the uicontrols, we can use this to
% retreive the values of the controls.
editTags = {'DivPerDeg', 'XLow', 'XHigh', 'YLow', 'YHigh'};

% grab the values (note: I like this one-liner!)
vals = cellfun(@(x)str2double(get(pKids(arrayfun(@(y)strcmp(get(y,'Tag'), x), pKids)), 'String')), editTags)';

% delete old heatmap, contour, and color bar objects.
delete([dataStruct.handles.hHtMp, dataStruct.handles.hCntr, dataStruct.handles.hColrBar])

% build new EMPTY ones
hTemp = buildHeatMap(vals(2:3)', vals(4:5)', vals(1), dataStruct.handles.hPlotAx, dataStruct.handles.hColBrAx);
dataStruct.handles.hHtMp    = hTemp(1);
dataStruct.handles.hCntr    = hTemp(2);
dataStruct.handles.hColrBar = hTemp(3);

% set axis limits
set(dataStruct.handles.hPlotAx, 'XLim', vals(2:3)', 'YLim', vals(4:5)');

% reconstruct
updateHeatMap([], [], dataStruct)
end

function figSave_callback(hObject, eventdata, dataStruct)

kids = get(get(hObject, 'Parent'), 'Children');

fileBox = kids(strcmp(get(kids, 'Tag'), 'FileName'));

disp('Saving Figure file...')
hgsave(get(get(hObject, 'Parent'), 'Parent'), ['/Users/klab/Documents/amar/gui2/physiology/saccade_heatmaps/' get(fileBox, 'String') '.fig'])
disp('HeatMap Figure Saved!')
end

function hTargetLoc_ButtonDownFcn(hObject, eventdata, dataStruct)

ptXYs   = cell2mat(get(hObject, {'XData', 'YData'}));
whichPt = all(bsxfun(@eq, dataStruct.X_Y_Complete(:,1:2), ptXYs),2);
whPDS   = all(bsxfun(@eq, dataStruct.PDS.targXY, ptXYs), 2);

% label the trials with the locked target location as state 1.6 to avoid
% data from those trials being used in map building.
try
    dataStruct.badPoints(whPDS) = true;
catch me
    keyboard
end

dataStruct.X_Y_Complete(whichPt, 3:5) = repmat([0, NaN, NaN], nnz(whichPt),1);

updateTargetsPlot([],[],dataStruct);
updateHeatMap([],[],dataStruct);

end

function hHeatMapType_ButtonDownFcn(hObject, eventdata, dataStruct)
switch get(hObject, 'Value')
    case 0
        set(hObject, 'String', 'Spikes-Based HeatMap');
    case 1
        set(hObject, 'String', 'PkV-Based HeatMap');
end
updateHeatMap(hObject, eventdata, dataStruct);
end

function hHeatMapTgtOrSacXY_Callback(hObject, eventdata, dataStruct)

switch get(hObject, 'Value')
    case 0
        set(hObject, 'String', 'Tgt-Based XY');
    case 1
        set(hObject, 'String', 'Sac-Based XY');
end
updateHeatMap(hObject, eventdata, dataStruct);

end

function mapLoad_callback(hObject, eventdata, dataStruct)

fnobj = findobj(get(get(hObject, 'Parent'), 'Children'), 'Tag', 'FileName');
[f, p] = uigetfile('*.mat');
set(fnobj, 'String', f(1:find(f=='.', 1, 'first')-1));
data = load([p,f]);

data = data.data;

try
    F = TriScatteredInterp(data(:,1:2), data(:,3));
catch me
    keyboard
end

if ~isprop(dataStruct, 'vMap');
addprop(dataStruct, 'vMap');
end
dataStruct.vMap = F;
set(get(get(dataStruct.handles.hTPanel, 'Parent'), 'Parent'), 'UserData', dataStruct);
updateHeatMap(hObject, eventdata, dataStruct);
end

%%%% Define create functions
function hTrialMarkersMenu_CreateFcn(hObject, eventdata, dataStruct)

% if there's no data in the PDS yet, don't try to populate the menu with
% information.
if isempty(dataStruct.PDS)
    % do nothing
else
    % What are the fieldnames of the PDS?
    PDSfields   = fieldnames(dataStruct.PDS);
    
    % Which PDS fieldnames start with "time"?
    timeFields = cell2mat(cellfun(@(x)(~isempty(x) && x==1), strfind(PDSfields, 'time'),'UniformOutput',false));
    
    % if this is the object creation call, use the hObject input to set the
    % string of the menu, otherwise, use the handle stored in datastruct.
    if ishandle(hObject)
        hUse = hObject;
    else
        hUse = dataStruct.handles.TMMenu;
    end
    
    % if this list matches the list that's already attached to the pulldown
    % menu, do nothing, otherwise populate the fieldnames into the menu,
    % and set one of them as active.
    if ~all(strcmp(PDSfields(timeFields), get(hUse, 'String')))
        % Put those fieldnames into the menu
        set(hUse, 'String', PDSfields(timeFields), 'Visible', 'on');
        
        % if the field "timetfon" is in the list (time that the target flash
        % happened), let's set the menu to this value.
        if any(strcmp(PDSfields(timeFields),'timetfon'))
            set(hUse, 'Value', find(strcmp(PDSfields(timeFields),'timetfon')))
        end
    end
    
end
end

%%%% Define other functions

function h = buildHeatMap(hmXLims, hmYLims, divPerDeg, ax, ax2)
% build the heatmap, fit-contour, and colorbar objects.
nXDiv       = round(range(hmXLims)/divPerDeg) + 1;
nYDiv       = round(range(hmYLims)/divPerDeg) + 1;
h(1)        = pcolor(ax, linspace(hmXLims(1),hmXLims(2), nXDiv), linspace(hmYLims(1),hmYLims(2),nYDiv), NaN(nYDiv,nXDiv));
warning('off','MATLAB:contour:NonFiniteData')
[~, h(2)]   = contour(ax, linspace(hmXLims(1),hmXLims(2), nXDiv), linspace(hmYLims(1),hmYLims(2),nYDiv), NaN(nYDiv,nXDiv), 'LineWidth', 1.5, 'LineColor', [1 1 1]);
h(3)        = pcolor(ax2, [0,1], linspace(0,1,100), NaN(100,2));
set(h(1), 'HitTest', 'off', 'EdgeColor', 'none');
set(h(2), 'HitTest', 'off');
set(h(3), 'EdgeColor', 'none');
end

function dataStruct = makeTimingPanel(dataStruct, hMainFigure)

hTimingPanel        = uipanel(...
    'Tag', 'hTimingPanel', ...
    'Parent', hMainFigure, ...
    'Title','Spike-Timing Window Selection', ...
    'TitlePosition', 'centertop', ...
    'FontSize',12,...
    'ForeGroundColor', [0.6 0 0], ...
    'ShadowColor', [1 0 0], ...
    'Position',[0.76 0.925 0.235 0.05]);

hTrialMarkersMenu   =   uicontrol(...    % list of available types of plot
    'Tag', 'hTrialMarkersMenu', ...
    'Parent', hTimingPanel, ...
    'Tag', 'Trial Markers Menu', ...
    'Units','normalized',...
    'Position',[0.305 0.03 0.4 0.7],...
    'HandleVisibility','callback', ...
    'Visible', 'Off',...
    'Style','popupmenu',...
    'CreateFcn', {@hTrialMarkersMenu_CreateFcn, dataStruct}, ...
    'Callback', @hTrialMarkersMenu_Callback);

hTimeWindowLow      =   uicontrol(...    % minimum relative time window for spike-inclusion
    'Tag', 'hTimeWindowLow', ...
    'Parent', hTimingPanel, ...
    'Units','normalized',...
    'Position',[0.04 0.25 0.25 0.55],...
    'HandleVisibility','callback', ...
    'Style','edit',...
    'Value', 50, ...
    'String', num2str(50), ...
    'Callback', @hTimeWindow_Callback);

hTimeWindowHigh     =   uicontrol(...    % maximum relative time window for spike-inclusion
    'Tag', 'hTimeWindowHigh', ...
    'Parent', hTimingPanel, ...
    'Units','normalized',...
    'Position',[0.72 0.25 0.25 0.55],...
    'HandleVisibility','callback', ...
    'Style','edit',...
    'Value', 200, ...
    'String', num2str(200), ...
    'Callback', @hTimeWindow_Callback);

% Put handles in dataStruct
dataStruct.handles.hTPanel  = hTimingPanel;
dataStruct.handles.TMMenu   = hTrialMarkersMenu;
dataStruct.handles.TLow     = hTimeWindowLow;
dataStruct.handles.THigh    = hTimeWindowHigh;
end

function dataStruct = makeHeatMapPropsPanel(dataStruct, hMainFigure, defProps)
% make a uipanel to contain the controls for the appearance of the heatmap
hHeatMapPropsPanel  = uipanel(...
    'Tag', 'hSpikeAxes3b', ...
    'Parent', hMainFigure, ...
    'Title','HeatMap Properties', ...
    'TitlePosition', 'centertop', ...
    'FontSize',12,...
    'ForeGroundColor', [0 0 0.6], ...
    'ShadowColor', [0 0 1], ...
    'Position',[0.76 0.8 0.235 0.1]);

hHeatMapXLimText    = uicontrol(...
    'Tag', 'hHeatMapXLimText', ...
    'Parent', hHeatMapPropsPanel, ...
    'Units','normalized',...
    'Style', 'text', ...
    'Position', [0.025 0.78 0.2 0.2], ...
    'String', 'X-Lims', ...
    'ForeGroundColor', [0 0 0.6], ...
    'FontSize', 11, ...
    'FontAngle', 'italic');

hHeatMapYLimText    = uicontrol(...
    'Tag', 'hHeatMapYLimText', ...
    'Parent', hHeatMapPropsPanel, ...
    'Units','normalized',...
    'Style', 'text', ...
    'Position', [0.175 0.78 0.2 0.2], ...
    'String', 'Y-Lims', ...
    'ForeGroundColor', [0 0 0.6], ...
    'FontSize', 11, ...
    'FontAngle', 'italic');

hHeatMapDPDText     = uicontrol(...
    'Tag', 'hHeatMapDPDText', ...
    'Parent', hHeatMapPropsPanel, ...
    'Units','normalized',...
    'Style', 'text', ...
    'Position', [0.4 0.78 0.2 0.2], ...
    'String', 'Div / Deg', ...
    'ForeGroundColor', [0 0 0.6], ...
    'FontSize', 11, ...
    'FontAngle', 'italic');

hHeatMapXlimLow     =   uicontrol(...
    'Parent', hHeatMapPropsPanel, ...
    'Units','normalized',...
    'Position',[0.05 0.35 0.15 0.2],...
    'HandleVisibility','callback', ...
    'Style','edit',...
    'String', num2str(defProps(2)), ...
    'Tag', 'XLow', ...
    'Callback', {@HeatMapProps_Callback, dataStruct});

hHeatMapXlimHigh    =   uicontrol(...
    'Parent', hHeatMapPropsPanel, ...
    'Units','normalized',...
    'Position',[0.05 0.55 0.15 0.2],...
    'HandleVisibility','callback', ...
    'Style','edit',...
    'String', num2str(defProps(3)), ...
    'Tag', 'XHigh', ...
    'Callback', {@HeatMapProps_Callback, dataStruct});

hHeatMapYlimLow     =   uicontrol(...
    'Parent', hHeatMapPropsPanel, ...
    'Units','normalized',...
    'Position',[0.21 0.35 0.15 0.2],...
    'HandleVisibility','callback', ...
    'Style','edit',...
    'String', num2str(defProps(4)), ...
    'Tag', 'YLow', ...
    'Callback', {@HeatMapProps_Callback, dataStruct});

hHeatMapYlimHigh    =   uicontrol(...
    'Parent', hHeatMapPropsPanel, ...
    'Units','normalized',...
    'Position',[0.21 0.55 0.15 0.2],...
    'HandleVisibility','callback', ...
    'Style','edit',...
    'String', num2str(defProps(5)), ...
    'Tag', 'YHigh', ...
    'Callback', {@HeatMapProps_Callback, dataStruct});

hHeatMapDivPerDeg   =   uicontrol(...
    'Parent', hHeatMapPropsPanel, ...
    'Units','normalized',...
    'Position',[0.425 0.55 0.15 0.2],...
    'HandleVisibility','callback', ...
    'Style','edit',...
    'String', num2str(defProps(1)), ...
    'Tag', 'DivPerDeg', ...
    'Callback', {@HeatMapProps_Callback, dataStruct});

hHeatMapTgtOrSacXY   =   uicontrol(...
    'Parent', hHeatMapPropsPanel, ...
    'Units','normalized',...
    'Position',[0.625 0.15 0.3 0.6],...
    'HandleVisibility','callback', ...
    'Style','togglebutton',...
    'String', 'Tgt-Based XY', ...
    'Tag', 'TgtOrSacXY', ...
    'Callback', {@hHeatMapTgtOrSacXY_Callback, dataStruct});

% store panel handle in dataStruct, and store toggle-button handle, cuz
% it's easier to access from another function call that way.
dataStruct.handles.hHMPanel = hHeatMapPropsPanel;
dataStruct.handles.mapXYtog = hHeatMapTgtOrSacXY;
end

function dataStruct = makeFitPropsPanel(dataStruct, hMainFigure)
% make a uipanel to contain the controls for the appearance of the heatmap
hFitPropsPanel  = uipanel(...
    'Parent', hMainFigure, ...
    'Title','Fit Properties', ...
    'Tag', 'RFFitPropsPanel', ...
    'TitlePosition', 'centertop', ...
    'FontSize',12,...
    'ForeGroundColor', [0 0 0.6], ...
    'ShadowColor', [0 0 1], ...
    'Position',[0.76 0.58 0.235 0.2]);

hMeanText          = uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Style', 'text', ...
    'Position', [0.02 0.8 0.2 0.2], ...
    'String', 'Mu:', ...
    'Tag','MeanText',...
    'ForeGroundColor', [0 0 0.6], ...
    'FontSize', 14, ...
    'FontAngle', 'italic',...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left');

hMu1                =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.025 0.6 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'Mu1', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hMu2                =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.025 0.415 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'Mu2', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hMu3                =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.025 0.24 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'Mu3-R', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hMu4                =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.025 0.065 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'Mu4-THETA', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hSigmaText          = uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Style', 'text', ...
    'Position', [0.16 0.8 0.2 0.2], ...
    'String', 'Sigma:', ...
    'Tag', 'SigmaText',...
    'ForeGroundColor', [0 0 0.6], ...
    'FontSize', 14, ...
    'FontAngle', 'italic',...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left');

hSigma11            =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.165 0.6 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'hSigma11', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hSigma21            =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.165 0.415 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'hSigma21', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hSigma12            =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.3 0.6 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'hSigma12', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hSigma22            =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.3 0.415 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'hSigma22', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hRadiusText         = uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Style', 'text', ...
    'Position', [0.45 0.8 0.2 0.2], ...
    'String', 'Radii:', ...
    'Tag', 'RadiusText',...
    'ForeGroundColor', [0 0 0.6], ...
    'FontSize', 14, ...
    'FontAngle', 'italic',...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left');

hRadVal1            =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.475 0.6 0.2 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'RadiusVal', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hRadVal2            =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.475 0.415 0.2 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'RadiusVal2', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hRadVal3            =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.475 0.23 0.2 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'RadiusVal3', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hRadVal4            =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.6 0.6 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'RadiusVal4', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hRadVal5            =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.6 0.415 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'RadiusVal5', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hRadVal6            =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.6 0.23 0.15 0.2],...
    'Style','text',...
    'String', num2str(1), ...
    'Tag', 'RadiusVal6', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left');

hAlphaText          = uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Style', 'text', ...
    'Position', [0.75 0.8 0.2 0.2], ...
    'String', 'Alphas:', ...
    'Tag', 'RadiusText',...
    'ForeGroundColor', [0 0 0.6], ...
    'FontSize', 14, ...
    'FontAngle', 'italic',...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left');

hAlphaVal1          =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.75 0.635 0.2 0.2],...
    'Style','edit',...
    'String', '25', ...
    'Tag', 'AlphaVal1', ...
    'FontSize', 14,...
    'Callback', {@updateFit, dataStruct});

hAlphaVal2          =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.75 0.435 0.2 0.2],...
    'Style','edit',...
    'String', '50', ...
    'Tag', 'AlphaVal2', ...
    'FontSize', 14,...
    'Callback', {@updateFit, dataStruct});

hAlphaVal3          =   uicontrol(...
    'Parent', hFitPropsPanel, ...
    'Units','normalized',...
    'Position',[0.75 0.26 0.2 0.2],...
    'Style','edit',...
    'String', '75', ...
    'Tag', 'AlphaVal3', ...
    'FontSize', 14,...
    'Callback', {@updateFit, dataStruct});

% store panel handel in dataStruct
dataStruct.handles.hFitPanel = hFitPropsPanel;
end

function dataStruct = makeTargetSelectPanel(dataStruct, hMainFigure)
% make a uipanel to contain the controls for the appearance of the heatmap
hTSelectPanel       = uipanel(...
    'Tag', 'hTSelectPanel', ...
    'Parent', hMainFigure, ...
    'Title','Target Location Selection', ...
    'TitlePosition', 'centertop', ...
    'FontSize',12,...
    'ForeGroundColor', [0 0 0.6], ...
    'ShadowColor', [0 0 1], ...
    'Position',[0.76 0.455 0.235 0.125]);

hRadioGrp1          = uibuttongroup('Parent', hTSelectPanel, ...
    'Tag', 'hRadioGrp1', ...
    'Units','normalized',...
    'Position', [0.025 0.525 0.4 0.4]);

hRadioButton1       =   uicontrol(...
    'Tag', 'hRadioButton1', ...
    'Parent', hRadioGrp1, ...
    'Units','normalized',...
    'Position',[0.025 0.55 0.95 0.5],...
    'Style','radiobutton',...
    'String', 'Multiple Locations');

hRadioButton2       =   uicontrol(...
    'Tag', 'hRadioButton2', ...
    'Parent', hRadioGrp1, ...
    'Units','normalized',...
    'Position',[0.025 0.05 0.95 0.5],...
    'Style','radiobutton',...
    'String', 'Single Location');

hXText              = uicontrol(...
    'Tag', 'hXText', ...
    'Parent', hTSelectPanel, ...
    'Units', 'Normalized', ...
    'Style', 'text', ...
    'String', 'X-Loc:', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'Right', ...
    'Position', [0.525 0.6 0.125 0.2]);

hYText              = uicontrol(...
    'Tag', 'hYText', ...
    'Parent', hTSelectPanel, ...
    'Units', 'Normalized', ...
    'Style', 'text', ...
    'String', 'Y-Loc:', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'Right', ...
    'Position', [0.525 0.15 0.125 0.2]);

hXVal               = uicontrol(...
    'Tag', 'hXVal', ...
    'Parent', hTSelectPanel, ...
    'Units', 'Normalized', ...
    'Style', 'edit', ...
    'String', '0', ...
    'FontSize', 14, ...
    'Position', [0.675 0.625 0.125 0.2]);

hYVal              = uicontrol(...
    'Tag', 'hYVal', ...
    'Parent', hTSelectPanel, ...
    'Units', 'Normalized', ...
    'Style', 'edit', ...
    'String', '0', ...
    'FontSize', 14, ...
    'Position', [0.675 0.175 0.125 0.2]);

% store panel handel in dataStruct
dataStruct.handles.hTSelectPanel = hTSelectPanel;
dataStruct.handles.hRadioButton1 = hRadioButton1;
dataStruct.handles.hRadioButton2 = hRadioButton2;
dataStruct.handles.hXVal = hXVal;
dataStruct.handles.hYVal = hYVal;

end

function dataStruct = makeMapTypeButton(dataStruct, hMainFigure)

set(hMainFigure, 'Units', 'normalized');
hMapType            = uicontrol(...
    'Parent', hMainFigure, ...
    'Tag','Heat Map Type', ...
    'FontSize',12,...
    'Units', 'normalized',...
    'Position',[0.55 0.03 0.1 0.175], ...
    'HandleVisibility','callback', ...
    'Callback', {@hHeatMapType_ButtonDownFcn, dataStruct}, ...
    'Style', 'togglebutton',...
    'Visible', 'On',...
    'String', 'Spikes-Based HeatMap');

set(hMainFigure, 'Units', 'pixels');

% Put handles in dataStruct
dataStruct.handles.hMapType  = hMapType;

end

function dataStruct = makeFigureSavePanel(dataStruct, hMainFigure)

hFigSavePanel       = uipanel(...
    'Tag','hFigSavePanel', ...
    'Parent', hMainFigure, ...
    'Units', 'Normalized', ...
    'Title','Figure Saving', ...
    'TitlePosition', 'centertop', ...
    'FontSize',12,...
    'ForeGroundColor', [0 0.6 0], ...
    'ShadowColor', [0 1 0], ...
    'Position',[0.825 0.03 0.125 0.175]);

hFileNameText       = uicontrol(...
    'Tag','hFileNameText', ...
    'Parent', hFigSavePanel, ...
    'Style', 'text', ...
    'String', 'File Name:', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'Units', 'Normalized', ...
    'Position', [0.025 0.65 0.4 0.1]);

hFileNameBox        = uicontrol(...
    'Tag','hFileNameBox', ...
    'Parent', hFigSavePanel, ...
    'Style', 'edit', ...
    'String', 'heatMapFig_', ...
    'FontSize', 14, ...
    'Units', 'Normalized', ...
    'Tag', 'FileName', ...
    'Position', [0.025 0.475 0.8 0.15]);

hFigureSaveButton   = uicontrol(...
    'Tag','hFigureSaveButton', ...
    'Parent', hFigSavePanel, ...
    'Style', 'pushbutton', ...
    'String', 'Save', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'Units', 'Normalized', ...
    'Position', [0.025 0.3 0.8 0.125], ...
    'Callback', {@figSave_callback, dataStruct});

% Put handles in dataStruct
dataStruct.handles.hSpkPnl  = hFigSavePanel;

end

function dataStruct = makePkVMapLoadPanel(dataStruct, hMainFigure)

hMapLoadPanel       = uipanel(...
    'Tag', 'hMapLoadPanel', ...
    'Parent', hMainFigure, ...
    'Units', 'Normalized', ...
    'Title','Peak Velocity Map Loading', ...
    'TitlePosition', 'centertop', ...
    'FontSize',12,...
    'ForeGroundColor', [0 0.6 0.6], ...
    'ShadowColor', [0 1 1], ...
    'Position',[0.675 0.03 0.125 0.175]);

hFileNameText       = uicontrol(...
    'Tag', 'hFileNameText', ...
    'Parent', hMapLoadPanel, ...
    'Style', 'text', ...
    'String', 'File Name:', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'Units', 'Normalized', ...
    'Position', [0.025 0.65 0.4 0.1]);

hFileNameDisp        = uicontrol(...
    'Tag', 'hFileNameDisp', ...
    'Parent', hMapLoadPanel, ...
    'Style', 'text', ...
    'String', 'No Map Loaded', ...
    'FontSize', 14, ...
    'Units', 'Normalized', ...
    'Tag', 'FileName', ...
    'Position', [0.025 0.475 0.8 0.15]);

hFigureSaveButton   = uicontrol(...
    'Tag', 'hFigureSaveButton', ...
    'Parent', hMapLoadPanel, ...
    'Style', 'pushbutton', ...
    'String', 'Load', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'Units', 'Normalized', ...
    'Position', [0.025 0.3 0.8 0.125], ...
    'Callback', {@mapLoad_callback, dataStruct});

% Put handles in dataStruct
dataStruct.handles.hMpLdPnl  = hMapLoadPanel;

end

function dataStruct = makeDataStruct

dataStruct          = SimpleClass;

dsProps(1)          = addprop(dataStruct, 'X_Y_Complete');
dsProps(2)          = addprop(dataStruct, 'handles');
dsProps(3)          = addprop(dataStruct, 'PDS');
dsProps(4)          = addprop(dataStruct, 'rfFit');
dsProps(5)          = addprop(dataStruct, 'badPoints');

dsProps(1).SetObservable = true;
dsProps(3).SetObservable = true;
dsProps(4).SetObservable = true;

end

function dataStruct = dummyPDS(dataStruct)

% if we're making a dummy PDS, let's make a gmdistribution object to
% generate spikes with in a structured way.
rotMat = @(theta)[cosd(theta) -sind(theta); sind(theta) cosd(theta)];
tempRotMat = rotMat(rand*90);
dataStruct.PDS.gmObj = gmdistribution([sign(randn)*(7+rand*2) sign(randn)*(7+rand*2)], tempRotMat*[rand*5 + 3 0; 0 rand*5 + 3]*tempRotMat');
nTrials = 60;
dataStruct.X_Y_Complete         = [dataStruct.X_Y_Complete; [-20 + rand(nTrials-length(dataStruct.X_Y_Complete(:,1)),1)*40, -15 + rand(nTrials-length(dataStruct.X_Y_Complete(:,1)),1)*30, zeros(nTrials-length(dataStruct.X_Y_Complete(:,1)), 1), NaN(nTrials-length(dataStruct.X_Y_Complete(:,1)),2)]];
dataStruct.X_Y_Complete(:,3)    = 1;
dataStruct.PDS.targXY           = dataStruct.X_Y_Complete(:,1:2);
dataStruct.PDS.sptimes          = cellfun(@(x)x(x<5),cellfun(@(x)cumsum(exprnd(1/x, 1, 1000)), num2cell(100*dataStruct.PDS.gmObj.pdf(dataStruct.PDS.targXY)/dataStruct.PDS.gmObj.pdf(dataStruct.PDS.gmObj.mu)), 'UniformOutput', 0'), 'UniformOutput', 0');
dataStruct.PDS.spikes           = cellfun(@(x)ones(length(x),1), dataStruct.PDS.sptimes, 'UniformOutput',false);
dataStruct.PDS.state            = repmat([1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 3, 3, 3.1, 3.2]', nTrials/10, 1);
dataStruct.PDS.timeTON          = randn(nTrials,1) + 1.5;
dataStruct.PDS.timeSCON         = randn(nTrials,1) + 1.5;
dataStruct.PDS.peakVel          = sqrt(dataStruct.PDS.targXY(:,1).^2 + dataStruct.PDS.targXY(:,2).^2)*50;
dataStruct.PDS.preSacXY         = normrnd(0, 0.1, nTrials, 2);
dataStruct.PDS.postSacXY        = dataStruct.PDS.targXY + normrnd(0,0.4, nTrials, 2);
end

function dataStruct = initTargetLocs(dataStruct)
nXpts                           = 5;
nYpts                           = 5;
dataStruct.X_Y_Complete         = sortrows([repmat(linspace(-10, 10, nXpts)', nYpts, 1), reshape(repmat(linspace(-10, 10, nYpts), nXpts, 1), nYpts*nXpts, 1), zeros(nYpts*nXpts, 1), NaN(nYpts*nXpts, 2)], [1 2]);
oPt                             = all(bsxfun(@eq, dataStruct.X_Y_Complete(:,1:3), [0 0 0]),2);
dataStruct.X_Y_Complete(oPt,:)  = [];
dataStruct.X_Y_Complete(:,1:2)  = dataStruct.X_Y_Complete(randperm(nYpts*nXpts-1)',1:2);
end

function dataStruct = updatePlots(hObject, eventdata, dataStruct)

% updates various plots with spike data after PDS is modified
updateHeatMap([], [], dataStruct);
updateRasters([], [], dataStruct);

end

function updateTargetsPlot(hObject, eventdata, dataStruct)

% Do we need to add a new plot object or just change colors? Compare number
% of plot objects to length of points-list.
nPnts   = size(dataStruct.X_Y_Complete,1);
nPlts   = size(dataStruct.handles.hTPlots,1);

% dataStruct.handles.hScPlt   = hSacEndLoc;
% dataStruct.handles.hScPlts  = hSacEndLocs;
% dataStruct.handles.hSTCL    = hTargSacConLine;
% dataStruct.handles.hSTCLs   = hTargSacConLines;

% add new plot objects if needed
if nPnts ~= nPlts
    dataStruct.handles.hTPlots = [copyobj(dataStruct.handles.hUnvisT, repmat(get(dataStruct.handles.hTPlots(1,1), 'Parent'), nPnts-nPlts, 1)); dataStruct.handles.hTPlots];
    dataStruct.handles.hScPlts = [copyobj(dataStruct.handles.hScPlt, repmat(get(dataStruct.handles.hScPlts(1,1), 'Parent'), nPnts-nPlts, 1)); dataStruct.handles.hScPlts];
    dataStruct.handles.hSTCLs  = [copyobj(dataStruct.handles.hSTCL, repmat(get(dataStruct.handles.hSTCLs(1,1), 'Parent'), nPnts-nPlts, 1)); dataStruct.handles.hSTCLs];
end

% position plot objects;
set(dataStruct.handles.hTPlots, ...
    {'XData'}, num2cell(dataStruct.X_Y_Complete(:,1)), ...
    {'YData'}, num2cell(dataStruct.X_Y_Complete(:,2)));

% fill in target locations that have been completed
doneGrp     = dataStruct.X_Y_Complete(:,3) == 1;
if nnz(doneGrp)
    set(dataStruct.handles.hTPlots(doneGrp), ...
        {'MarkerFaceColor'}, mat2cell(zeros(sum(doneGrp),3), ones(sum(doneGrp),1), 3));
    
    set(dataStruct.handles.hScPlts(doneGrp), ...
        {'MarkerFaceColor'}, mat2cell(zeros(sum(doneGrp),3), ones(sum(doneGrp),1), 3));
    
    set(dataStruct.handles.hScPlts(doneGrp), ...
        {'XData'}, num2cell(dataStruct.X_Y_Complete(doneGrp,4)), ...
        {'YData'}, num2cell(dataStruct.X_Y_Complete(doneGrp,5)));
    
    set(dataStruct.handles.hSTCLs(doneGrp), ...
        {'XData'}, mat2cell([dataStruct.X_Y_Complete(doneGrp,1), dataStruct.X_Y_Complete(doneGrp,4)], ones(nnz(doneGrp),1), 2), ...
        {'YData'}, mat2cell([dataStruct.X_Y_Complete(doneGrp,2), dataStruct.X_Y_Complete(doneGrp,5)], ones(nnz(doneGrp),1), 2));
end

if nnz(~doneGrp)
    set(dataStruct.handles.hTPlots(~doneGrp), ...
        {'MarkerFaceColor'}, mat2cell(ones(sum(~doneGrp),3), ones(sum(~doneGrp),1), 3));
end

% reassign data structure to figure handle
set(get(get(dataStruct.handles.hTPlots(1,1), 'Parent'), 'Parent'), 'UserData', dataStruct);

drawnow;
end

function updateHeatMap(hObject, eventdata, dataStruct)

flatten = @(x)x(:);
repPts  = @(x,y)repmat(x,y,1);
newCData    = [];

if isempty(dataStruct.PDS)
elseif  nnz(dataStruct.PDS.state == 1.5)>2
    
    
    if ~isempty(dataStruct.badPoints)
        dataStruct.PDS.state(find(dataStruct.badPoints)) = 1.6;
    end
    
    % only use at correctly performed trials.
    g           = dataStruct.PDS.state == 1.5;
    
    % determine desired time-window based on GUI objects
    posFields   = get(dataStruct.handles.TMMenu, 'String');
    currField   = posFields{get(dataStruct.handles.TMMenu, 'Value')};
    
    % how many trials are we dealing with?
    nTrials     = nnz(g);
    
    % if we have enough unique target-location trials, make a map
    if size(unique(dataStruct.PDS.targXY(g,:),'rows'),1) > 2
        
        % make sure we don't get an annoying warning from
        % triscatteredinterp
        warning('off', 'MATLAB:TriScatteredInterp:DupPtsAvValuesWarnId');
        
        % what type of map are we making?
        switch get(dataStruct.handles.hMapType, 'Value')
            case 0 % spike-based.
                
                % if we've got spikes
                if ~all(cellfun(@isempty, dataStruct.PDS.sptimes))
                    % calculate spike counts in desired window
                    spCounts    = cellfun(@(x,y,a,b)nnz(x>(y+a) & x<(y+b)), flatten(dataStruct.PDS.sptimes(g)), flatten(num2cell(dataStruct.PDS.(currField)(g))), num2cell(get(dataStruct.handles.TLow, 'Value')/1000*ones(nTrials,1)), num2cell(get(dataStruct.handles.THigh, 'Value')/1000*ones(nTrials,1)));
                    
                    % fit X / Y / spike-count data to linear-interpolant "F".
                    if get(dataStruct.handles.mapXYtog, 'Value')
                        X = dataStruct.PDS.postSacXY(g,1);
                        Y = dataStruct.PDS.postSacXY(g,2);
                    else 
                        X = dataStruct.PDS.targXY(g,1);
                        Y = dataStruct.PDS.targXY(g,2);
                    end
                    F           = TriScatteredInterp(X, Y, spCounts);
                    
                    % fit gaussian to spike count data, we're going to use the linear
                    % interpolant to guess the parameters. But we only want to do this if
                    % we have enough data points! We need at least 8 since we have 7
                    % parameters.
                    if size(unique(dataStruct.PDS.targXY(g,:),'rows'),1) > 7
                        fitParamsGuess = calcFitGuess(F, dataStruct);
                        dataStruct.rfFit = gauss2D.fit([dataStruct.PDS.targXY(g,1), dataStruct.PDS.targXY(g,2)], spCounts, fitParamsGuess);
                    end
                else
                    F = TriScatteredInterp([0 0; 1 0; 0 1], [0; 0; 0]);
                end
            case 1
                % fit X / Y / peak-velocity data to linear-interpolant "F".
                % We're using saccade end-point for this map, not target
                % location...
                F           = TriScatteredInterp(dataStruct.PDS.postSacXY(g,1), dataStruct.PDS.postSacXY(g,2), flatten(dataStruct.PDS.peakVel(g)));
        end
        
        % how many x / y points do we have?
        [nY, nX]    = size(get(dataStruct.handles.hHtMp, 'CData'));
        
        % if we've got a pre-loaded vMap, and that's the type of map we're
        % presenting, use that preloaded vMap and take the difference
        % between the two for the result...
        if isprop(dataStruct, 'vMap') && get(dataStruct.handles.hMapType, 'Value')
            nc1    = reshape(F([flatten(repmat(get(dataStruct.handles.hHtMp, 'XData'), nY, 1)), repmat(get(dataStruct.handles.hHtMp, 'YData')', nX, 1)]), nY, nX);
            nc2    = reshape(dataStruct.vMap([flatten(repmat(get(dataStruct.handles.hHtMp, 'XData'), nY, 1)), repmat(get(dataStruct.handles.hHtMp, 'YData')', nX, 1)]), nY, nX);
            newCData = nc1-nc2;
        else
            % evaluate linear interpolant at grid-locations to get map intensity (color) data.
            newCData    = reshape(F([flatten(repmat(get(dataStruct.handles.hHtMp, 'XData'), nY, 1)), repmat(get(dataStruct.handles.hHtMp, 'YData')', nX, 1)]), nY, nX);
        end
        
        
        
        
        % update colorbar
        amin = nanmin(newCData(:));
        amax = nanmax(newCData(:));
        cmin = sign(amin)* abs(amin)/range(newCData(:));
        cmax = sign(amax)* abs(amax)/range(newCData(:));
        if all([cmin cmax] == 0) || all(isnan([cmin cmax]));
            cmin = 0;
            cmax = 1;
            amin = 0;
            amax = 1;
        end
        cBarData = repmat(linspace(cmin, cmax, 100)',1,2);
        cBarYTick = linspace(amin, amax, 11)';
        try
            set(dataStruct.handles.hColBrAx, 'YTickLabel', arrayfun(@(x)num2str(round(x*10)/10), cBarYTick, 'UniformOutput', false), 'CLim', [cmin cmax]);
        catch
            keyboard
        end
        set(dataStruct.handles.hColrBar, 'CData', cBarData);
        
        % update map with new color data
        set(dataStruct.handles.hHtMp, 'CData', newCData / range(newCData(:)));
        set(get(dataStruct.handles.hHtMp,'Parent'), 'CLim', [cmin cmax]);
        
        % reassign data structure to figure handle
        set(get(get(dataStruct.handles.hTPlots(1,1), 'Parent'), 'Parent'), 'UserData', dataStruct);
        drawnow;
    end
end

% if we just want to see the loaded PKV data.
if isempty(newCData) && isprop(dataStruct, 'vMap') && get(dataStruct.handles.hMapType, 'Value')
    % how many x / y points do we have?
    [nY, nX]    = size(get(dataStruct.handles.hHtMp, 'CData'));
    newCData    = reshape(dataStruct.vMap([flatten(repmat(get(dataStruct.handles.hHtMp, 'XData'), nY, 1)), repmat(get(dataStruct.handles.hHtMp, 'YData')', nX, 1)]), nY, nX);
    
    % update map with new color data
    try
        set(dataStruct.handles.hHtMp, 'CData', newCData / range(newCData(:)));
    catch me
        keyboard
    end
    
    
    % update colorbar
    cBarData = repmat(linspace(nanmin(newCData(:)) / max(flatten(newCData)), nanmax(newCData(:)) / max(flatten(newCData)), 100)', 1,2);
    cBarYTick = linspace(nanmin(newCData(:)), nanmax(newCData(:)), 11)';
    set(dataStruct.handles.hColBrAx, 'YTickLabel', arrayfun(@(x)num2str(round(x*10)/10), cBarYTick, 'UniformOutput', false));
    set(dataStruct.handles.hColrBar, 'CData', cBarData);
    
    % reassign data structure to figure handle
    set(get(get(dataStruct.handles.hTPlots(1,1), 'Parent'), 'Parent'), 'UserData', dataStruct);
    drawnow;
end

end

function updateRasters(hObject, eventdata, dataStruct)

flatten = @(x)x(:);

if isempty(dataStruct.PDS)
elseif dataStruct.PDS.state(end) == 1.5 && ~isempty(dataStruct.PDS.sptimes{end})
    
    % if we're here, there's a new raster line to plot, keep count of how
    % many raster lines we have...
    currRasterCount = get(dataStruct.handles.hRst, 'UserData');
    if isempty(currRasterCount)
        currRasterCount = 0;
    end
    newRasterCount = currRasterCount + 1;
    set(dataStruct.handles.hRst, 'UserData', newRasterCount);
    
    % with respect to which times are we interested in plotting spikes?
    relTimes = {'timetfon', 'timesacon', 'timereward'};
    
    %%% update spike-plot
    spTimes = dataStruct.PDS.sptimes{end}(logical(dataStruct.PDS.spikes{end}));
    
    % what do we want the half-length of the raster-lines to be?
    lineRad         = 0.4;
    
    % make new objects for the spikes.
    newRasters  = copyobj(dataStruct.handles.hRst, flipud(flatten(repmat([dataStruct.handles.hSpAx1, dataStruct.handles.hSpAx2, dataStruct.handles.hSpAx3], length(spTimes),1))));
    
    % set the properties of the new raster-objects
    set(newRasters, {'XData'}, mat2cell(repmat(spTimes(:),3,2) - repmat(flatten(repmat([dataStruct.PDS.timetfon(end), dataStruct.PDS.timesacon(end), dataStruct.PDS.timereward(end)], length(spTimes), 1)),1,2), ones(1,3*length(spTimes),1),2),...
        {'YData'}, mat2cell(repmat(newRasterCount,3*length(spTimes),2) + repmat([-1 1]*lineRad,3*length(spTimes),1), ones(1,3*length(spTimes),1),2));
    
    % bin all the spikes to plot an average
    for i = 1:length(relTimes)
        allSpTimes          = cell2mat(cellfun(@(x,y,z)x(logical(y))' - z, dataStruct.PDS.sptimes, dataStruct.PDS.spikes, num2cell(dataStruct.PDS.(relTimes{i})), 'UniformOutput', false)');
        [spBin{i}, binC{i}] = spikeBin(allSpTimes, 0.02);
    end
    
    % update the plots with the newly calculated data
    set([dataStruct.handles.hBSPlt1; dataStruct.handles.hBSPlt2; dataStruct.handles.hBSPlt3], {'XData'}, binC', {'YData'}, spBin');
    
    % update the x-limits on the binned-spike plotting axes
    set([dataStruct.handles.hSpAx1b; dataStruct.handles.hSpAx2b; dataStruct.handles.hSpAx3b], {'XLim'}, get([dataStruct.handles.hSpAx1; dataStruct.handles.hSpAx2; dataStruct.handles.hSpAx3], 'XLim'));
    
    % update the y-limits on the raster plots based on how many trials
    % we're plotting. If we've got 40 or fewer, keep the y-lims at 40,
    % otherwise, update...
    yplotmin = max([40 newRasterCount]);
    try
    set([dataStruct.handles.hSpAx1; dataStruct.handles.hSpAx2; dataStruct.handles.hSpAx3], {'YLim'},{[0 yplotmin]},{'YTick'},{0:10:yplotmin});
    catch
        keyboard
    end
    
    % reassign data structure to figure handle
    set(get(get(dataStruct.handles.hTPlots(1,1), 'Parent'), 'Parent'), 'UserData', dataStruct);
    drawnow;
end
end

function updateFit(hObject, eventdata, dataStruct)

% inline function definitions
flatten = @(x)x(:);
rotMat = @(theta)[cosd(theta) -sind(theta); sind(theta) cosd(theta)];

% grab children of the fit properties panel
fitKids = flipud(get(dataStruct.handles.hFitPanel,'Children'));

% grab X & Y data from contour plot, evaluate using current gaussian
% fit and update contour plot using result
[X, Y] = meshgrid(get(dataStruct.handles.hCntr, 'XData'), get(dataStruct.handles.hCntr, 'YData'));
[levels, radii] = dataStruct.rfFit.pctbound(cellfun(@str2double, get(fitKids(19:21), 'String'))/100);
set(dataStruct.handles.hCntr, 'ZData', reshape(dataStruct.rfFit.value([flatten(X), flatten(Y)]), size(X, 1), size(X, 2)), 'LevelList', levels,'HitTest','off');

% grab mean & sigma
mean = dataStruct.rfFit.mu;

% compute mean in polar coords.
meanpol = [norm(mean) atan2d(mean(2), mean(1))];
sigma = rotMat(dataStruct.rfFit.angle)*[dataStruct.rfFit.sigma(1) 0; 0 dataStruct.rfFit.sigma(2)]*rotMat(dataStruct.rfFit.angle)';
set(fitKids([2:5 7:10 12:17]), {'String'},arrayfun(@num2str,round(10*[mean(1) mean(2) meanpol(1) meanpol(2) sigma(1) sigma(2) sigma(3) sigma(4) radii']')/10,'UniformOutput',false));
end

function [n, binCenters] = spikeBin(spikeTimes, binWidth)

minTime     = floor(min(spikeTimes)*1000)/1000;
maxTime     = ceil(max(spikeTimes)*1000)/1000;
myEdges     = minTime:binWidth:maxTime;

if myEdges(end) < maxTime
    myEdges = [myEdges, maxTime];
end

n           = histc(spikeTimes, myEdges);
binCenters  = mean([myEdges(1:end-1); myEdges(2:end)]);
n           = n(1:end-1);
end

function c = myContourc(x,y,Z,level)
fh = figure('Visible','off');
c = contour(x,y,Z,level);
close(fh);
end

function pguess = calcFitGuess(F, dataStruct)

flatten = @(x)x(:);

% a grid of points to evaulate the linear interpolant "F" on.
[Xhm, Yhm] = meshgrid(get(dataStruct.handles.hHtMp,'XData'), get(dataStruct.handles.hHtMp,'YData'));

% find F's max.
interpMax = max(flatten(F(Xhm, Yhm)));

% the X/Y value corresponding to the maximum
[iPk,jPk] = ind2sub(size(Xhm), find(F(Xhm, Yhm) == interpMax));

% the guess for the mean is the coordinates of F's maximum
muGuess = [mean(flatten(Xhm(iPk, jPk))), mean(flatten(Yhm(iPk, jPk)))];

% calculate the contour of F at half it's max (for guessing sigma)
c2 = myContourc(linspace(min(flatten(Xhm)), max(flatten(Xhm)), length(unique(flatten(Xhm)))), linspace(min(flatten(Yhm)), max(flatten(Yhm)), length(unique(flatten(Yhm)))), F(Xhm, Yhm), interpMax/2);

% our guess for sigma is the max distance from the peak's coords to the
% halfmax contour.
sigmaGuess = max(sqrt(sum(bsxfun(@minus,c2(:,2:end), muGuess').^2)));

% put the guess together (we guess an angle of 1, an additive offset of 0,
% and a scaling factor based on the guess for mu/sigma.
pguess = [muGuess, sigmaGuess*[1, 1], 1, 0, interpMax/mvnpdf(muGuess,muGuess,sigmaGuess*eye(2))];
end