function p = plotWindowSetup(p)
%PLOTWINDOWSETUP Create the SRS online behavioral dashboard.
%
% Only successfully completed trials are added to behavioral plots. The
% status panel is refreshed after every attempted trial.

%% ------------------------------------------------------------
% Layout
% ------------------------------------------------------------

RewardPosition          = [0.06 0.84 0.61 0.12];
LuminancePosition       = [0.06 0.66 0.61 0.12];
PHighSalPosition        = [0.06 0.47 0.18 0.11];
PHighRewardPosition     = [0.275 0.47 0.18 0.11];
MedianRTPosition        = [0.49 0.47 0.18 0.11];
ExplorationPosition     = [0.06 0.26 0.61 0.15];
ChoiceEvolutionPosition = [0.06 0.02 0.61 0.16];
StatusPosition          = [0.70 0.01 0.285 0.98];

%% ------------------------------------------------------------
% Initialize online behavioral storage
% ------------------------------------------------------------

p.status.onlinePlot = struct( ...
    'trial',              [], ...
    'trialType',          [], ...       % 1 = congruent, 2 = conflict
    'nStim',              [], ...       % 1 = instruction, 2 = choice
    'choseHighSal',       [], ...
    'choseHighReward',    [], ...
    'rtMs',               [], ...
    'chosenTargetID',     [], ...
    'chosenRewardMs',     [], ...
    'previousRewardMs',   [], ...
    'switchedTarget',     []);

%% ------------------------------------------------------------
% Create window
% ------------------------------------------------------------

oldWin = findobj('Name', 'OnlinePlotWindow');
if ~isempty(oldWin)
    delete(oldWin);
end

p.draw.onlinePlotWindow = figure( ...
    'Position', [1200 100 1300 1100], ...
    'Name', 'OnlinePlotWindow', ...
    'NumberTitle', 'off', ...
    'Color', [1 1 1], ...
    'Visible', 'off', ...
    'NextPlot', 'add');

if ~isfield(p.trVarsInit, 'wantOnlinePlots') || ...
        ~p.trVarsInit.wantOnlinePlots
    return;
end

%% ------------------------------------------------------------
% Reward difference
% ------------------------------------------------------------

p.draw.onlinePlotAxes.rewardDiff = makeAxis( ...
    p.draw.onlinePlotWindow, RewardPosition, ...
    'Reward difference across successful trials', ...
    'Trial number', 'T1 - T2 reward (ms)');

p.draw.onlinePlotObj.rewardZero = plot( ...
    p.draw.onlinePlotAxes.rewardDiff, [0 10], [0 0], ':k', ...
    'LineWidth', 1.2);

p.draw.onlinePlotObj.rewardDiff = plot( ...
    p.draw.onlinePlotAxes.rewardDiff, NaN, NaN, '-', ...
    'Marker', '.', 'MarkerSize', 10, ...
    'Color', [0.00 0.45 0.74], 'LineWidth', 1.4);

text(p.draw.onlinePlotAxes.rewardDiff, 0.02, 0.88, ...
    'Positive = T1 richer', 'Units', 'normalized', 'FontSize', 9);
text(p.draw.onlinePlotAxes.rewardDiff, 0.02, 0.10, ...
    'Negative = T2 richer', 'Units', 'normalized', 'FontSize', 9);
set(p.draw.onlinePlotAxes.rewardDiff, 'XLim', [0 10], 'YLim', [-200 200]);

%% ------------------------------------------------------------
% Luminance difference
% ------------------------------------------------------------

p.draw.onlinePlotAxes.luminanceDiff = makeAxis( ...
    p.draw.onlinePlotWindow, LuminancePosition, ...
    'Luminance difference across successful trials', ...
    'Trial number', 'T1 - T2 task luminance');

p.draw.onlinePlotObj.luminanceZero = plot( ...
    p.draw.onlinePlotAxes.luminanceDiff, [0 10], [0 0], ':k', ...
    'LineWidth', 1.2);

p.draw.onlinePlotObj.luminanceDiff = plot( ...
    p.draw.onlinePlotAxes.luminanceDiff, NaN, NaN, '-', ...
    'Marker', '.', 'MarkerSize', 10, ...
    'Color', [0.47 0.67 0.19], 'LineWidth', 1.4);

text(p.draw.onlinePlotAxes.luminanceDiff, 0.02, 0.88, ...
    'Positive = T1 brighter', 'Units', 'normalized', 'FontSize', 9);
text(p.draw.onlinePlotAxes.luminanceDiff, 0.02, 0.10, ...
    'Negative = T2 brighter', 'Units', 'normalized', 'FontSize', 9);
set(p.draw.onlinePlotAxes.luminanceDiff, 'XLim', [0 10], 'YLim', [-12 12]);

%% ------------------------------------------------------------
% P(high salience)
% ------------------------------------------------------------

p.draw.onlinePlotAxes.pHighSal = makeCategoryAxis( ...
    p.draw.onlinePlotWindow, PHighSalPosition, ...
    'P(High salience)', 'Probability');

p.draw.onlinePlotObj.pHighSalChance = plot( ...
    p.draw.onlinePlotAxes.pHighSal, [0.5 2.5], [0.5 0.5], '--', ...
    'Color', 0.75 * [1 1 1], 'LineWidth', 1.1);

p.draw.onlinePlotObj.pHighSalConflict = bar( ...
    p.draw.onlinePlotAxes.pHighSal, 1, NaN, 0.55, ...
    'FaceColor', [0.85 0.33 0.10], 'EdgeColor', 'none');
p.draw.onlinePlotObj.pHighSalCongruent = bar( ...
    p.draw.onlinePlotAxes.pHighSal, 2, NaN, 0.55, ...
    'FaceColor', [0.00 0.45 0.74], 'EdgeColor', 'none');

%% ------------------------------------------------------------
% P(high reward)
% ------------------------------------------------------------

p.draw.onlinePlotAxes.pHighReward = makeCategoryAxis( ...
    p.draw.onlinePlotWindow, PHighRewardPosition, ...
    'P(High reward)', 'Probability');

p.draw.onlinePlotObj.pHighRewardChance = plot( ...
    p.draw.onlinePlotAxes.pHighReward, [0.5 2.5], [0.5 0.5], '--', ...
    'Color', 0.75 * [1 1 1], 'LineWidth', 1.1);

p.draw.onlinePlotObj.pHighRewardConflict = bar( ...
    p.draw.onlinePlotAxes.pHighReward, 1, NaN, 0.55, ...
    'FaceColor', [0.85 0.33 0.10], 'EdgeColor', 'none');
p.draw.onlinePlotObj.pHighRewardCongruent = bar( ...
    p.draw.onlinePlotAxes.pHighReward, 2, NaN, 0.55, ...
    'FaceColor', [0.00 0.45 0.74], 'EdgeColor', 'none');

%% ------------------------------------------------------------
% Median RT
% ------------------------------------------------------------

p.draw.onlinePlotAxes.medianRT = makeCategoryAxis( ...
    p.draw.onlinePlotWindow, MedianRTPosition, ...
    'Median RT', 'RT (ms)');
set(p.draw.onlinePlotAxes.medianRT, 'YLim', [0 500]);

p.draw.onlinePlotObj.medianRTConflict = bar( ...
    p.draw.onlinePlotAxes.medianRT, 1, NaN, 0.55, ...
    'FaceColor', [0.85 0.33 0.10], 'EdgeColor', 'none');
p.draw.onlinePlotObj.medianRTCongruent = bar( ...
    p.draw.onlinePlotAxes.medianRT, 2, NaN, 0.55, ...
    'FaceColor', [0.00 0.45 0.74], 'EdgeColor', 'none');

%% ------------------------------------------------------------
% Exploration: previous reward versus target switching
% ------------------------------------------------------------

p.draw.onlinePlotAxes.exploration = makeAxis( ...
    p.draw.onlinePlotWindow, ExplorationPosition, ...
    'Exploration: switch after previous successful choice reward', ...
    'Reward received on previous choice trial (ms)', ...
    'Switched T1/T2 identity');
set(p.draw.onlinePlotAxes.exploration, ...
    'YLim', [-0.12 1.12], ...
    'YTick', [0 1], ...
    'YTickLabel', {'Stay', 'Switch'});

p.draw.onlinePlotObj.explorationChance = plot( ...
    p.draw.onlinePlotAxes.exploration, [0 1], [0.5 0.5], '--', ...
    'Color', 0.80 * [1 1 1], 'LineWidth', 1.0);

p.draw.onlinePlotObj.explorationRaw = plot( ...
    p.draw.onlinePlotAxes.exploration, NaN, NaN, 'o', ...
    'LineStyle', 'none', ...
    'MarkerSize', 5, ...
    'MarkerFaceColor', [0.70 0.70 0.70], ...
    'MarkerEdgeColor', [0.45 0.45 0.45]);

p.draw.onlinePlotObj.explorationBinned = plot( ...
    p.draw.onlinePlotAxes.exploration, NaN, NaN, '-o', ...
    'Color', [0.49 0.18 0.56], ...
    'MarkerFaceColor', [0.49 0.18 0.56], ...
    'LineWidth', 2, 'MarkerSize', 6);

legend(p.draw.onlinePlotAxes.exploration, ...
    [p.draw.onlinePlotObj.explorationRaw, ...
     p.draw.onlinePlotObj.explorationBinned], ...
    {'Individual transitions', 'Binned P(switch)'}, ...
    'Location', 'best');

%% ------------------------------------------------------------
% Choice evolution
% ------------------------------------------------------------

p.draw.onlinePlotAxes.choiceEvolution = makeAxis( ...
    p.draw.onlinePlotWindow, ChoiceEvolutionPosition, ...
    'Choice evolution over successful choice trials', ...
    'Trial number', 'Cumulative P(High salience)');
set(p.draw.onlinePlotAxes.choiceEvolution, 'XLim', [0 10], 'YLim', [0 1]);

p.draw.onlinePlotObj.choiceChance = plot( ...
    p.draw.onlinePlotAxes.choiceEvolution, [0 10], [0.5 0.5], '--', ...
    'Color', 0.80 * [1 1 1], 'LineWidth', 1.1);

p.draw.onlinePlotObj.choiceConflict = plot( ...
    p.draw.onlinePlotAxes.choiceEvolution, NaN, NaN, '-', ...
    'Color', [0.85 0.33 0.10], 'LineWidth', 2);
p.draw.onlinePlotObj.choiceCongruent = plot( ...
    p.draw.onlinePlotAxes.choiceEvolution, NaN, NaN, '-', ...
    'Color', [0.00 0.45 0.74], 'LineWidth', 2);
p.draw.onlinePlotObj.choiceOverall = plot( ...
    p.draw.onlinePlotAxes.choiceEvolution, NaN, NaN, '--', ...
    'Color', [0.20 0.20 0.20], 'LineWidth', 1.5);

legend(p.draw.onlinePlotAxes.choiceEvolution, ...
    [p.draw.onlinePlotObj.choiceConflict, ...
     p.draw.onlinePlotObj.choiceCongruent, ...
     p.draw.onlinePlotObj.choiceOverall], ...
    {'Conflict', 'Congruent', 'Overall'}, ...
    'Location', 'southoutside', 'Orientation', 'horizontal');

%% ------------------------------------------------------------
% Status panel
% ------------------------------------------------------------

p.draw.onlinePlotObj.statusText = uicontrol( ...
    'Parent', p.draw.onlinePlotWindow, ...
    'Style', 'listbox', ...
    'Units', 'normalized', ...
    'Position', StatusPosition, ...
    'BackgroundColor', [0.97 0.97 0.97], ...
    'ForegroundColor', [0 0 0], ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'FixedWidth', ...
    'FontSize', 10, ...
    'String', {'Status will appear here'});

set(p.draw.onlinePlotWindow, 'Visible', 'on');

end

function ax = makeAxis(parentHandle, position, titleText, xLabelText, yLabelText)

ax = axes( ...
    'Parent', parentHandle, ...
    'Units', 'normalized', ...
    'Position', position, ...
    'TickDir', 'out', ...
    'LineWidth', 1, ...
    'XColor', [0 0 0], ...
    'YColor', [0 0 0], ...
    'NextPlot', 'add');

hold(ax, 'on');
box(ax, 'off');
title(ax, titleText, 'FontSize', 12, 'FontWeight', 'bold');
xlabel(ax, xLabelText, 'FontSize', 10);
ylabel(ax, yLabelText, 'FontSize', 10);

end

function ax = makeCategoryAxis(parentHandle, position, titleText, yLabelText)

ax = makeAxis(parentHandle, position, titleText, '', yLabelText);
set(ax, ...
    'XLim', [0.5 2.5], ...
    'YLim', [0 1], ...
    'XTick', [1 2], ...
    'XTickLabel', {'Conflict', 'Congruent'});

end
