function SELF_TEST_SRS_MORETRAINING_LOGIC
%SELF_TEST_SRS_MORETRAINING_LOGIC Hardware-free regression checks.
%
% Run from MATLAB before a behavioral session:
%   SELF_TEST_SRS_MORETRAINING_LOGIC

% These tests do not open Psychtoolbox, DATAPixx, audio or eye tracking.

taskFolder = fileparts(mfilename('fullpath'));
addpath(fullfile(taskFolder, 'supportFunctions'));

%% Cumulative RIGHT reward reduction
levels = 1:6;
actual = arrayfun(@(level) computeCorrectionRightReward( ...
    100, 0.5, level, 10), levels);
expected = [50 25 12 10 10 10];
assert(isequal(actual, expected), ...
    'Cumulative RIGHT reward sequence is incorrect.');

% A minimum above the original reward must never increase the reward.
assert(computeCorrectionRightReward(100, 0.5, 1, 200) == 100, ...
    'Configured minimum unexpectedly increased the original reward.');

%% Reduction advances only after another completed RIGHT choice
level = 1;
level = advanceCorrectionRightRewardReductionLevel(level, false, 0, false);
assert(level == 1, 'No-response trial changed the reduction level.');
level = advanceCorrectionRightRewardReductionLevel(level, false, 1, false);
assert(level == 1, 'Aborted RIGHT movement changed the reduction level.');
level = advanceCorrectionRightRewardReductionLevel(level, true, 1, false);
assert(level == 2, 'Completed RIGHT choice did not advance the level.');
level = advanceCorrectionRightRewardReductionLevel(level, true, 2, true);
assert(level == 2, 'Correct LEFT/high-reward choice changed the level.');

%% Trial-wise target delay randomization
rng(1);
nSamples = 500;
delays = nan(1, nSamples);
previous = NaN;
for iSample = 1:nSamples
    delays(iSample) = sampleTargetDelayMs(350, 650, previous);
    previous = delays(iSample);
end
assert(all(delays >= 350 & delays <= 650), ...
    'A sampled target delay was outside its configured range.');
assert(all(diff(delays) ~= 0), ...
    'Two consecutive target delays were identical.');
assert(numel(unique(delays)) > 200, ...
    'Target delay samples do not vary sufficiently.');
assert(sampleTargetDelayMs(500, 500, 500) == 500, ...
    'A fixed one-value delay range is not handled correctly.');

%% Every SRS paired-strobe field has a global PLDAPS code
codes = pds.initCodes;
requiredCodes = { ...
    'correctionTrialEnabled', 'correctionTrialActive', ...
    'correctionTrialRepetition', ...
    'correctionRightRewardReductionLevel', ...
    'correctionTrialMaxRepetition', 'correctionReduceRightReward', ...
    'correctionRightRewardMultiplier_x1000', ...
    'correctionRightRewardMinimumMs', ...
    'correctionRightRewardAppliedMs', ...
    'correctionOriginalRightRewardMs', ...
    'correctionSnapshotValid', 'delta'};
assert(all(isfield(codes, requiredCodes)), ...
    'One or more correction/delay strobe codes are missing.');

%% Reward-delivery consistency guard
p = makeCorrectionRewardTestStruct(50);
p = enforceCorrectionRewardDelivery(p);
assert(p.trData.correctionRewardConsistencyPassed == 1, ...
    'A consistent RIGHT correction reward failed validation.');
assert(p.trData.deliveredRewardDurationMs == 50, ...
    'The consistent RIGHT correction reward was not recorded.');

% Simulate a stale target/current duration. The guard must repair it to 50.
p = makeCorrectionRewardTestStruct(100);
p = enforceCorrectionRewardDelivery(p);
assert(p.trData.correctionRewardConsistencyPassed == 0, ...
    'A stale RIGHT correction reward was not detected.');
assert(p.trVars.currentRewardDuration == 50 && ...
        p.trVars.rewardDurationT1 == 50 && ...
        p.trData.deliveredRewardDurationMs == 50, ...
    'A stale RIGHT correction reward was not repaired before delivery.');

fprintf('SELF_TEST_SRS_MORETRAINING_LOGIC: all checks passed.\n');

end

function p = makeCorrectionRewardTestStruct(selectedRewardMs)
p = struct();
p.trVars = struct( ...
    'currentRewardDuration', selectedRewardMs, ...
    'correctionTrialActive', 1, ...
    'correctionReduceRightReward', 1, ...
    'correctionRightRewardAppliedMs', 50, ...
    'correctionRightRewardReductionLevel', 1, ...
    'correctionOriginalRightRewardMs', 100, ...
    'correctionRightRewardMinimumMs', 10, ...
    'rewardDurationRight', selectedRewardMs, ...
    'rewardDurationT1', selectedRewardMs, ...
    'rewardDurationT2', 200, ...
    'T1Side', 1, ...
    'T2Side', 2);
p.trData = struct('chosenSide', 1, 'chosenTargetID', 1);
end
