function p = extraWindowSetup(p)

%
% p = extraWindowSetup(p)
%
% Function in which we initialize the saccade mapping gui.

% if we're using the mapping gui, initialize it here
if p.trVarsInit.setTargLocViaGui
    
    % first check to see if there's already a gui open and close it.
    guiHandle = findall(0, 'Name', 'saccade mapping GUI');
    if ~isempty(guiHandle)
        close(guiHandle)
    end
    
    % open new gui window
    p.rig.guiData = saccadeGUI(false);
    
    % reposition saccade gui window relative to main gui window
    mainGuiPos = get(findall(0, 'Name', 'PLDAPS_vK2_GUI'), 'Position');
    set(p.rig.guiData.handles.hGui, 'Position', ...
        [sum([mainGuiPos([1 3]), 10]), mainGuiPos(2), 1500, 1200]);
end

if p.trVarsInit.wantOnlinePlots
% make a gui window to plot eye / target position information:
% make new plotting window for fixation / joystick press duration timing
% information:
p.draw.gazeVsTimeFig         = ...
    figure(...
    'Position', [10 800 1200 1200],...
    'Name','gazeVsTimeFig',...
    'NumberTitle','off',...
    'Color', 1 * [1 1 1],...
    'Visible','on',...
    'NextPlot','add');

% make axes for plotting eye position
p.draw.gazePosPlotAxes = ...
    axes(...
    'Parent', p.draw.gazeVsTimeFig, ...
    'Position', [0.06 0.375 0.875 0.275], ...
    'TickDir', 'Out', ...
    'LineWidth', 1, ...
    'XColor', 'none', ...
    'YColor', [0 0 0], ...
    'NextPlot', 'add', ...
    'Color', 'none' ...
    );

% make axes for plotting eye position
p.draw.fixTargPosPlotAxes = ...
    axes(...
    'Parent', p.draw.gazeVsTimeFig, ...
    'Position', [0.06 0.674 0.875 0.275], ...
    'TickDir', 'Out', ...
    'LineWidth', 1, ...
    'XColor', 'none', ...
    'NextPlot', 'add', ...
    'Color', 'none', ...
    'YLim', [-0.1 3.1] ...
    );

% make axes for plotting eye velocity
p.draw.gazeVelPlotAxes = ...
    axes(...
    'Parent', p.draw.gazeVsTimeFig, ...
    'Position', [0.06 0.075 0.875 0.275], ...
    'TickDir', 'Out', ...
    'LineWidth', 1, ...
    'XColor', [0 0 0], ...
    'YColor', [0 0 0], ...
    'NextPlot', 'add', ...
    'Color', 'none', ...
    'YLim', [0 1200] ...
    );

% add X / Y axis labels:
set(p.draw.gazePosPlotAxes.XAxis.Label, ...
    'String', 'Time from fixation acquisition (s)', ...
    'FontSize', 16 ...
    );
set(p.draw.gazePosPlotAxes.YAxis.Label, ...
    'String', 'Eye Position (deg)', ...
    'FontSize', 16 ...
    );
set(p.draw.gazeVelPlotAxes.YAxis.Label, ...
    'String', 'Eye Velocity (deg / s)', ...
    'FontSize', 16 ...
    );
set(p.draw.fixTargPosPlotAxes.YAxis.Label, ...
    'String', 'Target Position (deg)', ...
    'FontSize', 16 ...
    );


% Make plot objects for several features
% (1) X gaze
% (2) Y gaze
% (3) Target
% (4) Fixation
% (5) eye velocity
% (6) Saccade Onset
% (7) Saccade Offset
% (8) Velocity Threshold
p.draw.plotObs.xGaze    = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
    'Color', [0.2941         0    0.5725]);
p.draw.plotObs.yGaze    = plot(p.draw.gazePosPlotAxes, NaN, NaN, ...
    'Color', [0    0.4235    0.8196]);
p.draw.plotObs.tgt      = plot(p.draw.fixTargPosPlotAxes, NaN, NaN, ...
    'Color', [0.0471    0.4824    0.8627]);
p.draw.plotObs.fix      = plot(p.draw.fixTargPosPlotAxes, NaN, NaN, ...
    'Color', [0.1020    0.5216    1.0000]);
p.draw.plotObs.eyeVel   = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
    'Color', [0 0 0]);
p.draw.plotObs.sacOn    = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
    'Color', [0.8824    0.7451    0.4157]);
p.draw.plotObs.sacOff   = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
    'Color', [0.6000    0.3098         0]);
p.draw.plotObs.vThresh  = plot(p.draw.gazeVelPlotAxes, NaN, NaN, ...
    ':', 'LineWidth', 1.5, 'Color', [0.8275    0.3725    0.7176]);

% make legend objects for gaze plots:
p.draw.plotObs.fixTargLegend = legend(p.draw.fixTargPosPlotAxes, ...
    [p.draw.plotObs.fix, p.draw.plotObs.tgt], {'Fixation', 'Target'}, ...
    'Location', 'northwest', 'FontSize', 16, 'Box', 'Off');
p.draw.plotObs.gazePosLegend = legend(p.draw.gazePosPlotAxes, ...
    [p.draw.plotObs.xGaze, p.draw.plotObs.yGaze], ...
    {'Eye - X', 'Eye - Y'}, ...
    'Location', 'northwest', 'FontSize', 16, 'Box', 'Off');
p.draw.plotObs.gazeVelLegend = legend(p.draw.gazeVelPlotAxes, ...
    [p.draw.plotObs.eyeVel, p.draw.plotObs.vThresh, ...
    p.draw.plotObs.sacOn, p.draw.plotObs.sacOff], ...
    {'Eye - Velocity', 'Threshold', 'Sac. Onset', 'Sac. Offset'}, ...
    'Location', 'northwest', 'FontSize', 16, 'Box', 'Off');
end

%% Create figure for pkV, RT, and err visualization by factor level
% This figure shows saccade metrics for locations 1 and 3 broken down by
% the 4 experimental factors: salience, reward, probability, and stim type.
% Each trial contributes data points to multiple x-positions based on
% which factor levels apply to that trial.

% Close existing figure if present
metricsFigHandle = findall(0, 'Name', 'Saccade Metrics by Factor');
if ~isempty(metricsFigHandle)
    close(metricsFigHandle)
end

% Create new figure for metrics visualization (wider to accommodate 8 positions)
p.draw.metricsFig = figure(...
    'Position', [1220 200 1200 900], ...
    'Name', 'Saccade Metrics by Factor', ...
    'NumberTitle', 'off', ...
    'Color', [1 1 1], ...
    'Visible', 'on', ...
    'NextPlot', 'add');

% Define colors for the two target locations
locColors = struct();
locColors.loc1 = [0.850 0.325 0.098];  % orange for location 1
locColors.loc3 = [0.000 0.447 0.741];  % blue for location 3

% Define x-axis labels for the 8 factor levels
% 1=highSal, 2=lowSal, 3=highRwd, 4=lowRwd, 5=highProb, 6=lowProb, 7=face, 8=nonFace
factorLabels = {'Hi Sal', 'Lo Sal', 'Hi Rwd', 'Lo Rwd', ...
                'Hi Prob', 'Lo Prob', 'Face', 'Non-Face'};

% --- Peak Velocity (top row) ---
p.draw.pkVAxes = axes(...
    'Parent', p.draw.metricsFig, ...
    'Position', [0.06 0.71 0.92 0.24], ...
    'TickDir', 'out', ...
    'LineWidth', 1, ...
    'NextPlot', 'add', ...
    'XLim', [0.5 8.5], ...
    'XTick', 1:8, ...
    'XTickLabel', factorLabels, ...
    'FontSize', 10);
ylabel(p.draw.pkVAxes, 'Peak Velocity (deg/s)', 'FontSize', 12);
title(p.draw.pkVAxes, 'Saccade Peak Velocity by Factor', 'FontSize', 13, 'FontWeight', 'bold');

% Add vertical lines to separate factor pairs
for xLine = [2.5, 4.5, 6.5]
    plot(p.draw.pkVAxes, [xLine xLine], [0 2000], ':', 'Color', [0.7 0.7 0.7], 'LineWidth', 1);
end

% Create scatter and mean plot objects for pkV (8 factor levels x 2 locations)
p.draw.plotObs.pkVScatter = cell(8, 2);  % {factorLevel, locIdx}
p.draw.plotObs.pkVMean = cell(8, 2);
for iLevel = 1:8
    for iLoc = 1:2
        if iLoc == 1
            color = locColors.loc1;
        else
            color = locColors.loc3;
        end
        p.draw.plotObs.pkVScatter{iLevel, iLoc} = scatter(p.draw.pkVAxes, [], [], 40, color, ...
            'filled', 'MarkerFaceAlpha', 0.5);
        p.draw.plotObs.pkVMean{iLevel, iLoc} = plot(p.draw.pkVAxes, NaN, NaN, '_', ...
            'Color', color, 'MarkerSize', 20, 'LineWidth', 3);
    end
end

% --- Reaction Time (middle row) ---
p.draw.rtAxes = axes(...
    'Parent', p.draw.metricsFig, ...
    'Position', [0.06 0.40 0.92 0.24], ...
    'TickDir', 'out', ...
    'LineWidth', 1, ...
    'NextPlot', 'add', ...
    'XLim', [0.5 8.5], ...
    'XTick', 1:8, ...
    'XTickLabel', factorLabels, ...
    'FontSize', 10);
ylabel(p.draw.rtAxes, 'Reaction Time (ms)', 'FontSize', 12);
title(p.draw.rtAxes, 'Saccade Reaction Time by Factor', 'FontSize', 13, 'FontWeight', 'bold');

% Add vertical lines to separate factor pairs
for xLine = [2.5, 4.5, 6.5]
    plot(p.draw.rtAxes, [xLine xLine], [0 2000], ':', 'Color', [0.7 0.7 0.7], 'LineWidth', 1);
end

% Create scatter and mean plot objects for RT
p.draw.plotObs.rtScatter = cell(8, 2);
p.draw.plotObs.rtMean = cell(8, 2);
for iLevel = 1:8
    for iLoc = 1:2
        if iLoc == 1
            color = locColors.loc1;
        else
            color = locColors.loc3;
        end
        p.draw.plotObs.rtScatter{iLevel, iLoc} = scatter(p.draw.rtAxes, [], [], 40, color, ...
            'filled', 'MarkerFaceAlpha', 0.5);
        p.draw.plotObs.rtMean{iLevel, iLoc} = plot(p.draw.rtAxes, NaN, NaN, '_', ...
            'Color', color, 'MarkerSize', 20, 'LineWidth', 3);
    end
end

% --- Endpoint Error (bottom row) ---
p.draw.errAxes = axes(...
    'Parent', p.draw.metricsFig, ...
    'Position', [0.06 0.08 0.92 0.24], ...
    'TickDir', 'out', ...
    'LineWidth', 1, ...
    'NextPlot', 'add', ...
    'XLim', [0.5 8.5], ...
    'XTick', 1:8, ...
    'XTickLabel', factorLabels, ...
    'FontSize', 10);
ylabel(p.draw.errAxes, 'Endpoint Error (deg)', 'FontSize', 12);
title(p.draw.errAxes, 'Saccade Endpoint Error by Factor', 'FontSize', 13, 'FontWeight', 'bold');
xlabel(p.draw.errAxes, 'Factor Level', 'FontSize', 12);

% Add vertical lines to separate factor pairs
for xLine = [2.5, 4.5, 6.5]
    plot(p.draw.errAxes, [xLine xLine], [0 100], ':', 'Color', [0.7 0.7 0.7], 'LineWidth', 1);
end

% Create scatter and mean plot objects for err
p.draw.plotObs.errScatter = cell(8, 2);
p.draw.plotObs.errMean = cell(8, 2);
for iLevel = 1:8
    for iLoc = 1:2
        if iLoc == 1
            color = locColors.loc1;
        else
            color = locColors.loc3;
        end
        p.draw.plotObs.errScatter{iLevel, iLoc} = scatter(p.draw.errAxes, [], [], 40, color, ...
            'filled', 'MarkerFaceAlpha', 0.5);
        p.draw.plotObs.errMean{iLevel, iLoc} = plot(p.draw.errAxes, NaN, NaN, '_', ...
            'Color', color, 'MarkerSize', 20, 'LineWidth', 3);
    end
end

% Add legend using dummy scatter objects
hLoc1 = scatter(p.draw.pkVAxes, NaN, NaN, 60, locColors.loc1, 'filled');
hLoc3 = scatter(p.draw.pkVAxes, NaN, NaN, 60, locColors.loc3, 'filled');
legend(p.draw.pkVAxes, [hLoc1, hLoc3], {'Location 1', 'Location 3'}, ...
    'Location', 'northeast', 'FontSize', 10, 'Box', 'off');

% Store location colors and factor labels for use in updateOnlinePlots
p.draw.locColors = locColors;
p.draw.factorLabels = factorLabels;

end