%% SELF_TEST_UPLOADED_SESSION
% Test de non-regression pour la session 20260720_t1112_srsSmooth_training.
%
% Ce script verifie trois niveaux :
%   1. Le chargeur retrouve exactement les valeurs attendues dans les 99
%      fichiers trialXXXX.mat transmis.
%   2. Les statistiques principales sont coherentes avec ces donnees.
%   3. L'orchestrateur complet produit les CSV, le rapport et le fichier MAT.
%
% Ce test est volontairement strict. Une assertion qui echoue indique soit
% que le dossier selectionne n'est pas la session de reference, soit qu'une
% modification du code a change le resultat attendu.

clear;
clc;
close all;

%% 1. Ajouter les fonctions d'analyse au MATLAB path
analysisFolder = fileparts(mfilename('fullpath'));
if isempty(analysisFolder)
    analysisFolder = pwd;
end
addpath(analysisFolder);

%% 2. Localiser la session de reference
% Le premier chemin correspond a l'organisation visible sur la machine du
% laboratoire. Les deux autres permettent de tester une copie extraite a
% proximite du dossier d'analyse.
sessionName = '20260720_t1112_srsSmooth_training';
candidates = { ...
    fullfile('/home/herman_lab/Documents/PLDAPS_vK2_MASTER', ...
        'tasks', 'SRS_Task_Smooth', 'output', sessionName), ...
    fullfile(fileparts(analysisFolder), sessionName), ...
    fullfile(pwd, sessionName)};

sessionFolder = '';
for iCandidate = 1:numel(candidates)
    if isfolder(candidates{iCandidate})
        sessionFolder = candidates{iCandidate};
        break;
    end
end

if isempty(sessionFolder)
    sessionFolder = uigetdir(pwd, [ ...
        'Choisir le dossier ' sessionName]);
    if isequal(sessionFolder, 0)
        error('Aucun dossier de session selectionne.');
    end
end

fprintf('Session testee :\n%s\n\n', sessionFolder);

%% 3. Tester le chargement et les variables derivees
[T, meta] = srs_load_session(sessionFolder);

assert(height(T) == 99, ...
    'Attendu : 99 fichiers de tentative. Observe : %d.', height(T));
assert(sum(T.GoodTrial) == 99, ...
    'Attendu : 99 essais reussis.');
assert(sum(T.GoodTrial & T.IsInstruction) == 20, ...
    'Attendu : 20 essais instruction.');
assert(sum(T.GoodChoice) == 79, ...
    'Attendu : 79 choix a deux cibles.');
assert(sum(T.GoodChoice & T.IsCongruent) == 39, ...
    'Attendu : 39 choix congruents.');
assert(sum(T.GoodChoice & T.IsConflict) == 40, ...
    'Attendu : 40 choix en conflit.');

% Cette session a ete executee avec les contournements de debug actifs.
assert(all(T.PassEye == 1), ...
    'Attendu : passEye=1 sur toutes les tentatives.');
assert(all(T.PassJoy == 1), ...
    'Attendu : passJoy=1 sur toutes les tentatives.');
assert(all(T.MouseEyeSim == 0), ...
    'Attendu : mouseEyeSim=0 sur toutes les tentatives.');
assert(meta.dataLikelySimulated, ...
    'La session devrait etre identifiee comme simulee/debug.');
assert(meta.nRealEyeChoices == 0, ...
    'Aucun choix ne devrait etre eligible a l inference comportementale.');

% Dans cette version de la tache, passEye choisit automatiquement la cible
% riche sur les essais a deux cibles. La cible riche est T2 dans ce bloc.
assert(all(T.RichTarget(T.GoodChoice) == 2), ...
    'Attendu : T2 est riche dans tous les choix de ce bloc.');
assert(all(T.ChosenTarget(T.GoodChoice) == 2), ...
    'Attendu : tous les choix a deux cibles vont vers T2.');
assert(sum(T.ChoseRich(T.GoodChoice)) == 79, ...
    'Attendu : 79/79 choix de la cible riche.');

% Le cote de T2 alterne selon le plan : 40 choix a droite et 39 a gauche.
assert(sum(T.GoodChoice & T.ChosenSide == 1) == 40, ...
    'Attendu : 40 choix a droite.');
assert(sum(T.GoodChoice & T.ChosenSide == 2) == 39, ...
    'Attendu : 39 choix a gauche.');
assert(all(T.ChoiceMappingValid(T.GoodChoice)), ...
    'Chaque cote choisi doit correspondre au cote de T2.');

% Online plots de reference.
assert(sum(T.ChoseHighSalience( ...
        T.GoodChoice & T.IsCongruent)) == 39, ...
    'Attendu : 39/39 choix haute saillance en congruent.');
assert(sum(T.ChoseHighSalience( ...
        T.GoodChoice & T.IsConflict)) == 0, ...
    'Attendu : 0/40 choix haute saillance en conflit.');

% Les timestamps de saccade simules ne donnent pas de RT valide selon la
% definition fixOff vers saccadeOnset.
assert(sum(isfinite(T.ReactionTimeMs)) == 0, ...
    'Attendu : aucun RT saccadique valide.');
assert(meta.mappingErrors == 0, ...
    'Attendu : aucune incoherence identite/cote.');

%% 4. Tester les statistiques principales
quickOptions = struct();
quickOptions.nPermutations = 100;
quickOptions.randomSeed = 20260720;
quickOptions.rollingWindow = 20;

stats = srs_compute_statistics(T, meta, quickOptions);

assert(height(stats.blockTable) == 1, ...
    'Attendu : un seul bloc sauvegarde.');
assert(stats.blockTable.ExpectedTrials(1) == 100, ...
    'Attendu : 100 essais programmes dans le bloc.');
assert(stats.blockTable.GoodTrials(1) == 99, ...
    'Attendu : 99 essais reussis sauvegardes.');
assert(stats.blockTable.TrialsMissing(1) == 1, ...
    'Attendu : un essai programme non sauvegarde.');
assert(~stats.interpretation.inferenceAllowed, ...
    'L inference animale doit etre desactivee pour cette session.');
assert(~isfinite(stats.engagement.estimatedDisengagementAttempt), ...
    'Aucun point d ennui ne doit etre infere en mode debug.');
assert(~isempty(stats.psychometricTable), ...
    'La table psychometrique descriptive devrait etre disponible.');

%% 5. Tester la chaine complete et l'ecriture des resultats
% Les figures sont desactivees ici pour que le test fonctionne egalement
% sur une machine sans affichage graphique. RUN_ONE_SRS_SESSION les active.
testOutput = tempname;
fullOptions = quickOptions;
fullOptions.makeFigures = false;
fullOptions.saveFigures = false;
fullOptions.saveMatlabFigures = false;
fullOptions.outputRoot = testOutput;
fullOptions.verbose = false;

results = srs_run_analysis({sessionFolder}, fullOptions);
assert(isfolder(results.sessions(1).outputFolder), ...
    'Le dossier de sortie complet n a pas ete cree.');

requiredFiles = { ...
    'trial_table.csv', ...
    'summary_statistics.csv', ...
    'balance_checks.csv', ...
    'bias_statistics.csv', ...
    'strategy_comparison.csv', ...
    'conditional_associations.csv', ...
    'choice_evolution_early_late.csv', ...
    'psychometric_binned.csv', ...
    'online_choice_statistics.csv', ...
    'online_timeseries_statistics.csv', ...
    'reaction_time_statistics.csv', ...
    'outcomes.csv', ...
    'block_completion.csv', ...
    'engagement_early_vs_late.csv', ...
    'logistic_models.csv', ...
    'exploration_summary.csv', ...
    'exploration_binned.csv', ...
    'analysis_report.txt', ...
    'analysis_results.mat'};

for iFile = 1:numel(requiredFiles)
    filePath = fullfile(results.sessions(1).outputFolder, ...
        requiredFiles{iFile});
    assert(isfile(filePath), 'Fichier de sortie manquant : %s', filePath);
end

%% 6. Afficher le verdict
fprintf('\n============================================================\n');
fprintf('SELF-TEST SRS : PASS\n');
fprintf('Toutes les valeurs de reference et les sorties ont ete verifiees.\n');
fprintf('Sorties temporaires du test :\n%s\n', ...
    results.sessions(1).outputFolder);
fprintf('============================================================\n');
