function p = initCorrectionControlWindow(p)
%INITCORRECTIONCONTROLWINDOW Create live controls for correction trials.
%
% The controls are read before every trial, so they remain editable while
% the task is running. Closing the window does not stop the task; settings
% then fall back to the latest values stored in p.trVarsGuiComm.

if ~controlWindowEnabled(p)
    return
end

% Remove a stale window from a previous initialization.
stale = findall(0, 'Type', 'figure', 'Name', 'SRS correction controls');
if ~isempty(stale)
    delete(stale);
end

if isfield(p.draw, 'correctionControlFigure') && ...
        isgraphics(p.draw.correctionControlFigure)
    delete(p.draw.correctionControlFigure);
end

fig = figure( ...
    'Name', 'SRS correction controls', ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Color', [0.94 0.94 0.94], ...
    'Units', 'pixels', ...
    'Position', [100 720 470 610], ...
    'HandleVisibility', 'callback');

uicontrol(fig, 'Style', 'text', 'String', 'Correction parameters', ...
    'Units', 'normalized', 'Position', [0.05 0.935 0.90 0.045], ...
    'FontWeight', 'bold', 'FontSize', 12, ...
    'HorizontalAlignment', 'left', 'BackgroundColor', get(fig, 'Color'));

hEnable = uicontrol(fig, 'Style', 'checkbox', ...
    'String', 'Enable correction trials', ...
    'Units', 'normalized', 'Position', [0.06 0.870 0.72 0.045], ...
    'Value', getInitialLogical(p, 'correctionTrial', false), ...
    'BackgroundColor', get(fig, 'Color'));

hBothSides = uicontrol(fig, 'Style', 'checkbox', ...
    'String', 'Correct low-reward choices on LEFT and RIGHT', ...
    'Units', 'normalized', 'Position', [0.06 0.815 0.86 0.045], ...
    'Value', getInitialLogical(p, 'correctionBothSides', false), ...
    'BackgroundColor', get(fig, 'Color'));

uicontrol(fig, 'Style', 'text', 'String', 'Maximum forced repetitions', ...
    'Units', 'normalized', 'Position', [0.06 0.750 0.56 0.038], ...
    'HorizontalAlignment', 'left', 'BackgroundColor', get(fig, 'Color'));
hMax = uicontrol(fig, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.68 0.745 0.22 0.046], ...
    'String', num2str(getInitialNumeric(p, ...
    'correctionTrialMaxRepetition', 15)), 'BackgroundColor', [1 1 1]);

hReduce = uicontrol(fig, 'Style', 'checkbox', ...
    'String', ['Reduce RIGHT reward during RIGHT-triggered ' ...
    'correction repeats'], ...
    'Units', 'normalized', 'Position', [0.06 0.675 0.88 0.055], ...
    'Value', getInitialLogical(p, 'correctionReduceRightReward', false), ...
    'BackgroundColor', get(fig, 'Color'));

uicontrol(fig, 'Style', 'text', 'String', 'RIGHT reward multiplier (0-1)', ...
    'Units', 'normalized', 'Position', [0.06 0.615 0.56 0.038], ...
    'HorizontalAlignment', 'left', 'BackgroundColor', get(fig, 'Color'));
hMultiplier = uicontrol(fig, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.68 0.610 0.22 0.046], ...
    'String', num2str(getInitialNumeric(p, ...
    'correctionRightRewardMultiplier', 0.50), '%.3f'), ...
    'BackgroundColor', [1 1 1]);

uicontrol(fig, 'Style', 'text', 'String', 'Minimum RIGHT reward (ms)', ...
    'Units', 'normalized', 'Position', [0.06 0.555 0.56 0.038], ...
    'HorizontalAlignment', 'left', 'BackgroundColor', get(fig, 'Color'));
hMinimum = uicontrol(fig, 'Style', 'edit', ...
    'Units', 'normalized', 'Position', [0.68 0.550 0.22 0.046], ...
    'String', num2str(getInitialNumeric(p, ...
    'correctionRightRewardMinimumMs', 1)), 'BackgroundColor', [1 1 1]);

uicontrol(fig, 'Style', 'text', 'String', 'Live status', ...
    'Units', 'normalized', 'Position', [0.05 0.490 0.90 0.040], ...
    'FontWeight', 'bold', 'HorizontalAlignment', 'left', ...
    'BackgroundColor', get(fig, 'Color'));

hStatus = uicontrol(fig, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.06 0.145 0.88 0.340], ...
    'String', {'Waiting for first trial'}, ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [1 1 1], 'FontName', 'FixedWidth');

uicontrol(fig, 'Style', 'text', ...
    'Units', 'normalized', 'Position', [0.06 0.035 0.88 0.085], ...
    'String', ['Changes are applied before the next trial. RIGHT reward ' ...
    'reduction is used only when the incorrect trigger choice was RIGHT.'], ...
    'HorizontalAlignment', 'left', 'BackgroundColor', get(fig, 'Color'));

p.draw.correctionControlFigure = fig;
p.draw.correctionControl.enable = hEnable;
p.draw.correctionControl.bothSides = hBothSides;
p.draw.correctionControl.maxRepetition = hMax;
p.draw.correctionControl.reduceRightReward = hReduce;
p.draw.correctionControl.rightRewardMultiplier = hMultiplier;
p.draw.correctionControl.rightRewardMinimumMs = hMinimum;
p.draw.correctionControl.statusText = hStatus;

p = updateCorrectionControlWindow(p);

end

function tf = controlWindowEnabled(p)
tf = true;
if isfield(p, 'trVarsInit') && isfield(p.trVarsInit, 'correctionControlWindow')
    tf = logical(p.trVarsInit.correctionControlWindow);
end
end

function value = getInitialNumeric(p, name, defaultValue)
value = defaultValue;
containers = {'trVarsGuiComm', 'trVars', 'trVarsInit'};
for i = 1:numel(containers)
    c = containers{i};
    if isfield(p, c) && isfield(p.(c), name)
        candidate = p.(c).(name);
        if (isnumeric(candidate) || islogical(candidate)) && ...
                isscalar(candidate) && isfinite(double(candidate))
            value = double(candidate);
            return
        end
    end
end
end

function value = getInitialLogical(p, name, defaultValue)
value = logical(getInitialNumeric(p, name, double(defaultValue)));
end
