function p = initDirectRgbExperimenterPreview(p)
%INITDIRECTRGBEXPERIMENTERPREVIEW Create an exp-only C24 task preview.
%
% In C24 the DATAPixx console output mirrors the subject RGB image, so the
% dual-CLUT trick used by L48 cannot hide overlays from the subject. This
% separate MATLAB figure shows target windows and the rich-target frame on
% the experimenter desktop without drawing them into the subject stream.

if ~previewEnabled(p)
    return
end

if isfield(p.draw, 'directRgbPreviewFigure') && ...
        isgraphics(p.draw.directRgbPreviewFigure)
    delete(p.draw.directRgbPreviewFigure);
end

position = [100 150 720 520];
if isfield(p.trVarsInit, 'directRgbPreviewPosition') && ...
        isnumeric(p.trVarsInit.directRgbPreviewPosition) && ...
        numel(p.trVarsInit.directRgbPreviewPosition) == 4
    position = double(p.trVarsInit.directRgbPreviewPosition(:)');
end
position = [1800 50 720 520];
fig = figure( ...
    'Name', 'SRS EXP-only direct-RGB preview', ...
    'NumberTitle', 'off', ...
    'Color', [0.12 0.12 0.12], ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Units', 'pixels', ...
    'Position', position, ...
    'HandleVisibility', 'callback');

ax = axes('Parent', fig, ...
    'Color', [0 0 0], ...
    'XColor', [0.85 0.85 0.85], ...
    'YColor', [0.85 0.85 0.85], ...
    'Box', 'on', ...
    'DataAspectRatio', [1 1 1], ...
    'NextPlot', 'add');
xlabel(ax, 'Horizontal position (deg)');
ylabel(ax, 'Vertical position (deg)');
title(ax, 'Waiting for first trial', 'Color', [1 1 1]);

p.draw.directRgbPreviewFigure = fig;
p.draw.directRgbPreviewAxes = ax;

end

function tf = previewEnabled(p)
tf = isfield(p, 'trVarsInit') && ...
    isfield(p.trVarsInit, 'directRgbExperimenterPreview') && ...
    logical(p.trVarsInit.directRgbExperimenterPreview);
end
