function [staAccum, staSpikeCount] = updateSTA(stimType, ...
    staAccum, staSpikeCount, spikeTimesPerChan, noiseOnTime, frameDurS, ...
    stimTensor, trialStartFrame, nFramesTrial, nLags)
% updateSTA  Stim-type dispatcher for online STA accumulation.
%
%   [staAccum, staSpikeCount] = updateSTA(stimType, ...
%       staAccum, staSpikeCount, spikeTimesPerChan, noiseOnTime, ...
%       frameDurS, stimTensor, trialStartFrame, nFramesTrial, nLags)
%
%   Routes to the per-stim-type estimator. stimType is the string from
%   p.init.stimType; the dispatcher does not consult any settings file.
%
%   stimTensor is the per-type stimulus representation:
%     denseAchromatic / sparse : [nY, nX, nFrames] noise movie
%                                (uint8 or int8)
%     denseChromatic           : [nY, nX, 3, nFrames] single drive tensor
%                                (per-trial; sessionFormatVersion >= 2)
%
%   Active paths: denseAchromatic, sparse, denseChromatic.
%
%   checkerboard is NOT routed through this dispatcher. Its accumulator
%   has a different shape (struct with kernel + F1/F2 fields) and a
%   different call signature (per-trial polarity sequence + condition);
%   rfMap_finish.accumulateSTA branches and calls
%   updateSTA_checkerboard directly.

switch stimType
    case 'denseAchromatic'
        [staAccum, staSpikeCount] = updateSTA_denseAchromatic( ...
            staAccum, staSpikeCount, spikeTimesPerChan, noiseOnTime, ...
            frameDurS, stimTensor, trialStartFrame, nFramesTrial, ...
            nLags);

    case 'sparse'
        [staAccum, staSpikeCount] = updateSTA_sparse( ...
            staAccum, staSpikeCount, spikeTimesPerChan, noiseOnTime, ...
            frameDurS, stimTensor, trialStartFrame, nFramesTrial, ...
            nLags);

    case 'denseChromatic'
        [staAccum, staSpikeCount] = updateSTA_denseChromatic( ...
            staAccum, staSpikeCount, spikeTimesPerChan, noiseOnTime, ...
            frameDurS, stimTensor, trialStartFrame, nFramesTrial, ...
            nLags);

    case 'checkerboard'
        error('updateSTA:checkerboardNotDispatched', ...
            ['Checkerboard accumulation has a struct-shaped accumulator ' ...
             'and a different call signature; rfMap_finish.accumulateSTA ' ...
             'must call updateSTA_checkerboard directly, not via this ' ...
             'dispatcher.']);

    otherwise
        error('updateSTA:badStimType', ...
            ['Unrecognized stimType ''%s''. Expected one of: ' ...
             'denseAchromatic, denseChromatic, sparse, checkerboard.'], ...
            stimType);
end

end
